<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPublishable>false</IsPublishable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Version>$(MotelyVersion)</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DuckDB.NET.Data.Full" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Motely\Motely.csproj" />
  </ItemGroup>
</Project>
