using Motely.Filters;
using SharpYaml.Serialization;

namespace Motely.Filters.Jaml;

[YamlSerializable(typeof(JamlConfig))]
[YamlSerializable(typeof(JamlClauseSet))]
[YamlSerializable(typeof(JokerSourceConfig))]
[YamlSerializable(typeof(LegendaryJokerSourceConfig))]
[YamlSerializable(typeof(TarotCardSourceConfig))]
[YamlSerializable(typeof(SpectralCardSourceConfig))]
[YamlSerializable(typeof(StandardCardSourceConfig))]
[YamlSerializable(typeof(PlanetSourceConfig))]
[YamlSerializable(typeof(IJamlClause))]
[YamlSerializable(typeof(JamlClause))]
[YamlSerializable(typeof(RollClause))]
[YamlSerializable(typeof(IRollClause))]
[YamlSerializable(typeof(LogicClause))]
[YamlSerializable(typeof(AndClause))]
[YamlSerializable(typeof(OrClause))]
[YamlSerializable(typeof(JokerClause))]
[YamlSerializable(typeof(CommonJokerClause))]
[YamlSerializable(typeof(UncommonJokerClause))]
[YamlSerializable(typeof(RareJokerClause))]
[YamlSerializable(typeof(MixedJokerClause))]
[YamlSerializable(typeof(LegendaryJokerClause))]
[YamlSerializable(typeof(BossClause))]
[YamlSerializable(typeof(VoucherClause))]
[YamlSerializable(typeof(TagClause))]
[YamlSerializable(typeof(StartingDrawClause))]
[YamlSerializable(typeof(TarotCardClause))]
[YamlSerializable(typeof(SpectralCardClause))]
[YamlSerializable(typeof(StandardCardClause))]
[YamlSerializable(typeof(PlanetCardClause))]
[YamlSerializable(typeof(ErraticCardClause))]
[YamlSerializable(typeof(ErraticRankClause))]
[YamlSerializable(typeof(ErraticSuitClause))]
[YamlSerializable(typeof(LuckyMoneyClause))]
[YamlSerializable(typeof(LuckyMultClause))]
[YamlSerializable(typeof(MisprintMultClause))]
[YamlSerializable(typeof(WheelOfFortuneClause))]
[YamlSerializable(typeof(CavendishExtinctClause))]
[YamlSerializable(typeof(GrosMichelExtinctClause))]
[YamlSerializable(typeof(SpaceLevelupClause))]
[YamlSerializable(typeof(BusinessPayoutClause))]
[YamlSerializable(typeof(BloodstoneTriggerClause))]
[YamlSerializable(typeof(ParkingPayoutClause))]
[YamlSerializable(typeof(GlassDestroyClause))]
[YamlSerializable(typeof(WheelStaysFlippedClause))]
internal partial class JamlSerializerContext : YamlSerializerContext;
