using System;

namespace Motely.Filters;

/// <summary>
/// Rejects <see cref="LegendaryJokerClause"/> configs that can never match
/// <see cref="LegendarySoulMatcher"/>: shop booster slot 0 is always Buffoon before weighted packs, so The Soul /
/// legendary rolls cannot come from that slot.
/// <para>
/// Editor/schema: <c>jaml.schema.json</c> (generated by <c>JamlSchemaGenerator</c>) adds a draft-07 rule for soul/legendary
/// clauses so legacy <c>sources.boosterPacks</c> cannot be only slot 0. Split <c>arcanaBoosterPacks</c>/<c>spectralBoosterPacks</c>
/// combinations are not fully expressible in JSON Schema without false positives; this type keeps the full check.
/// </para>
/// </summary>
internal static class JamlSoulJokerStructuralValidation
{
    internal static void ValidateLegendaryJokerClauseOrThrow(LegendaryJokerClause clause)
    {
        SoulJokerSourceConfig n = clause.Sources.NormalizeSoulJokerBoostersIfEmpty();
        if (!IsLegendarySoulMatcherBoosterPathDead(n))
            return;

        throw new InvalidOperationException(
            "Soul joker: The Soul / legendary rolls only appear from arcana or spectral booster packs. "
                + "In Motely's shop pack stream, booster slot 0 is always the Buffoon pack (two jokers), then weighted packs. "
                + "Your sources only reference shop booster slot 0 (no arcana/spectral slot with index ≥ 1). "
                + "This filter matches zero seeds for every seed — remove the search or widen sources (e.g. boosterPacks: [0,1] or arcanaBoosterPacks: [1])."
        );
    }

    /// <summary>
    /// True when every targeted booster slot is 0 — slot 0 is never arcana/spectral in <see cref="LegendarySoulMatcher"/>.
    /// </summary>
    internal static bool IsLegendarySoulMatcherBoosterPathDead(SoulJokerSourceConfig normalized)
    {
        bool split =
            normalized.ArcanaBoosterPacks.Length > 0 || normalized.SpectralBoosterPacks.Length > 0;
        if (!split)
        {
            if (normalized.BoosterPacks.Length == 0)
                return false;

            int max = -1;
            for (int i = 0; i < normalized.BoosterPacks.Length; i++)
            {
                int p = normalized.BoosterPacks[i];
                if (p > max)
                    max = p;
            }
            return max <= 0;
        }

        int maxA = MaxOrMinus1(normalized.ArcanaBoosterPacks);
        int maxS = MaxOrMinus1(normalized.SpectralBoosterPacks);
        int maxCombined = Math.Max(maxA, maxS);
        return maxCombined <= 0;
    }

    private static int MaxOrMinus1(int[] arr)
    {
        if (arr.Length == 0)
            return -1;
        int m = arr[0];
        for (int i = 1; i < arr.Length; i++)
        {
            if (arr[i] > m)
                m = arr[i];
        }
        return m;
    }
}
