<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="DuckDB.NET.Data.Full" Version="1.4.4" />
    <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageVersion Include="McMaster.Extensions.CommandLineUtils" Version="5.0.0" />
    <PackageVersion Include="Terminal.Gui" Version="2.0.0-develop.5027" />
    <PackageVersion Include="YamlDotNet" Version="16.3.0" />
    <PackageVersion Include="Vecc.YamlDotNet.Analyzers.StaticGenerator" Version="16.3.0" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.1.1" />
    <PackageVersion Include="Microsoft.OpenApi" Version="2.0.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore.Annotations" Version="7.2.0" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageVersion Include="Scalar.AspNetCore" Version="1.2.3" />
  </ItemGroup>
</Project>
