export type ValidationState = 'required-incomplete' | 'optional-incomplete' | 'complete' | 'invalid' | 'metadata';
export declare const JAML_SCHEMA_VERSION: string;
export declare const jamlSchema: Record<string, unknown>;
export declare const METADATA_KEYS: string[];
export declare const SECTION_KEYS: string[];
export declare const CLAUSE_TYPE_KEYS: string[];
export declare const PROPERTY_KEYS: string[];
export declare const SOURCE_KEYS: string[];
export declare function getValidValuesForKey(key: string): readonly string[] | null;
export declare function getAvailablePropsForType(clauseType: string): string[];
export declare function isInvalidPropForType(prop: string, clauseType: string): boolean;
export declare function isInvalidValueForProp(value: string, prop: string, clauseType: string): boolean;
