import type { JokerRow } from './types'

/** Source list; may contain duplicate names — use `dedupeJokersByName`. */
export const DEFAULT_JOKERS: JokerRow[] = [
  { id: 1, name: 'Joker', humanoid: true, bg: '#6b21a8', notes: 'Jimbo face' },
  { id: 2, name: 'Greedy Joker', humanoid: true, bg: '#b45309', notes: 'Angry diamond face' },
  { id: 3, name: 'Lusty Joker', humanoid: true, bg: '#be123c', notes: 'Smug heart face' },
  { id: 4, name: 'Wrathful Joker', humanoid: true, bg: '#1e3a5f', notes: 'Rage spade face' },
  { id: 5, name: 'Gluttonous Joker', humanoid: true, bg: '#14532d', notes: 'Greedy club face' },
  { id: 6, name: 'Jolly Joker', humanoid: true, bg: '#dc2626', notes: 'Happy jester' },
  { id: 7, name: 'Zany Joker', humanoid: true, bg: '#7c3aed', notes: 'Manic jester' },
  { id: 8, name: 'Mad Joker', humanoid: true, bg: '#065f46', notes: 'Mad jester' },
  { id: 9, name: 'Crazy Joker', humanoid: true, bg: '#92400e', notes: 'Chaotic jester' },
  { id: 10, name: 'Droll Joker', humanoid: true, bg: '#1e3a5f', notes: 'Deadpan jester' },
  { id: 11, name: 'Sly Joker', humanoid: true, bg: '#7f1d1d', notes: 'Sly smirk' },
  { id: 12, name: 'Wily Joker', humanoid: true, bg: '#1a2e05', notes: 'Cunning grin' },
  { id: 13, name: 'Clever Joker', humanoid: true, bg: '#1e3a5f', notes: 'Thinking face' },
  { id: 14, name: 'Devious Joker', humanoid: true, bg: '#4a044e', notes: 'Devious face' },
  { id: 15, name: 'Crafty Joker', humanoid: true, bg: '#064e3b', notes: 'Scheming face' },
  {
    id: 16,
    name: 'Half Joker',
    humanoid: true,
    bg: '#374151',
    notes: 'Literally half a Jimbo face',
  },
  {
    id: 17,
    name: 'Joker Stencil',
    humanoid: false,
    bg: '#1f2937',
    notes: 'Spray paint stencil on card',
  },
  {
    id: 18,
    name: 'Four Fingers',
    humanoid: false,
    bg: '#1e3a5f',
    notes: 'Disembodied hand, no face',
  },
  { id: 19, name: 'Mime', humanoid: true, bg: '#1c1917', notes: 'Classic mime face B&W' },
  { id: 20, name: 'Credit Card', humanoid: false, bg: '#1e3a5f', notes: 'Credit card' },
  { id: 21, name: 'Ceremonial Dagger', humanoid: false, bg: '#1c1917', notes: 'Dagger' },
  { id: 22, name: 'Banner', humanoid: false, bg: '#b45309', notes: 'Banner/flag' },
  { id: 23, name: 'Mystic Summit', humanoid: false, bg: '#312e81', notes: 'Mountain peak' },
  { id: 24, name: 'Marble Joker', humanoid: false, bg: '#d1d5db', notes: 'Marble texture' },
  { id: 25, name: 'Loyalty Card', humanoid: false, bg: '#fbbf24', notes: 'Stamp card' },
  { id: 26, name: '8 Ball', humanoid: false, bg: '#111827', notes: 'Pool 8-ball' },
  { id: 27, name: 'Misprint', humanoid: false, bg: '#e5e7eb', notes: 'Misprinted card' },
  { id: 28, name: 'Dusk', humanoid: false, bg: '#312e81', notes: 'Twilight/dusk card' },
  { id: 29, name: 'Raised Fist', humanoid: false, bg: '#7f1d1d', notes: 'Fist, no face' },
  { id: 30, name: 'Chaos the Clown', humanoid: true, bg: '#dc2626', notes: 'Clown face, red' },
  { id: 31, name: 'Fibonacci', humanoid: false, bg: '#0f172a', notes: 'Spiral math' },
  { id: 32, name: 'Steel Joker', humanoid: false, bg: '#374151', notes: 'Steel texture' },
  { id: 33, name: 'Scary Face', humanoid: true, bg: '#1a0a0a', notes: 'Horror face' },
  { id: 34, name: 'Abstract Joker', humanoid: true, bg: '#312e81', notes: 'Abstract Jimbo face' },
  {
    id: 35,
    name: 'Delayed Gratification',
    humanoid: false,
    bg: '#065f46',
    notes: 'Abstract economy',
  },
  { id: 36, name: 'Hack', humanoid: false, bg: '#0f172a', notes: 'Computer glitch card' },
  {
    id: 37,
    name: 'Pareidolia',
    humanoid: false,
    bg: '#374151',
    notes: 'Pattern illusion in static',
  },
  { id: 38, name: 'Gros Michel', humanoid: false, bg: '#fde047', notes: 'Banana' },
  { id: 39, name: 'Even Steven', humanoid: true, bg: '#16a34a', notes: 'Chill dude face' },
  { id: 40, name: 'Odd Todd', humanoid: true, bg: '#b45309', notes: 'Wacky dude face' },
  { id: 41, name: 'Scholar', humanoid: true, bg: '#1e3a5f', notes: 'Academic character' },
  { id: 42, name: 'Business Card', humanoid: false, bg: '#f5f5f4', notes: 'Business card' },
  { id: 43, name: 'Supernova', humanoid: false, bg: '#0f172a', notes: 'Exploding star' },
  { id: 44, name: 'Ride the Bus', humanoid: true, bg: '#1e3a5f', notes: 'Character on a bus' },
  { id: 45, name: 'Space Joker', humanoid: false, bg: '#0f172a', notes: 'Space/cosmic card' },
  { id: 46, name: 'Egg', humanoid: false, bg: '#fef9c3', notes: 'Egg' },
  { id: 47, name: 'Burglar', humanoid: true, bg: '#1c1917', notes: 'Masked thief, has a face' },
  { id: 48, name: 'Blackboard', humanoid: true, bg: '#14532d', notes: 'Teacher at blackboard' },
  { id: 49, name: 'Ice Cream', humanoid: false, bg: '#fdf2f8', notes: 'Ice cream cone' },
  { id: 50, name: 'DNA', humanoid: false, bg: '#065f46', notes: 'DNA helix' },
  { id: 51, name: 'Vagabond', humanoid: true, bg: '#78350f', notes: 'Wanderer character' },
  { id: 52, name: 'Baron', humanoid: true, bg: '#1e3a5f', notes: 'Noble baron character' },
  { id: 53, name: 'Cloud 9', humanoid: false, bg: '#bfdbfe', notes: 'Cloud' },
  { id: 54, name: 'Rocket', humanoid: false, bg: '#0f172a', notes: 'Rocket ship' },
  { id: 55, name: 'Oops All 6s', humanoid: false, bg: '#dc2626', notes: 'Card covered in 6s' },
  { id: 56, name: 'The Idol', humanoid: false, bg: '#b45309', notes: 'Idol statue' },
  { id: 57, name: 'Seeing Double', humanoid: true, bg: '#7c3aed', notes: 'Double vision face' },
  { id: 58, name: 'Wee Joker', humanoid: true, bg: '#6d28d9', notes: 'Tiny Jimbo' },
  { id: 59, name: 'Card Sharp', humanoid: true, bg: '#1c1917', notes: 'Slick cardshark character' },
  { id: 60, name: 'Red Card', humanoid: false, bg: '#dc2626', notes: 'Red card' },
  { id: 61, name: 'Madness', humanoid: true, bg: '#7c3aed', notes: 'Manic face' },
  {
    id: 62,
    name: 'Photograph',
    humanoid: true,
    bg: '#f5f5f4',
    notes: 'Portrait photo, has a face',
  },
  { id: 63, name: 'Lucky Cat', humanoid: false, bg: '#fbbf24', notes: 'Maneki-neko, stylized' },
  { id: 64, name: 'Bull', humanoid: false, bg: '#92400e', notes: 'Bull head' },
  { id: 65, name: 'Diet Cola', humanoid: false, bg: '#dc2626', notes: 'Diet cola can' },
  {
    id: 66,
    name: 'Trading Card',
    humanoid: true,
    bg: '#dbeafe',
    notes: 'Sports card with character face',
  },
  { id: 67, name: 'Flash Card', humanoid: false, bg: '#fde047', notes: 'Study flash card' },
  { id: 68, name: 'Spare Trousers', humanoid: false, bg: '#1e40af', notes: 'Pants' },
  {
    id: 69,
    name: 'Ancient Joker',
    humanoid: true,
    bg: '#78350f',
    notes: 'Ancient face with snake motifs',
  },
  { id: 70, name: 'Ramen', humanoid: false, bg: '#fbbf24', notes: 'Bowl of ramen' },
  { id: 71, name: 'Walkie Talkie', humanoid: false, bg: '#374151', notes: 'Radio' },
  { id: 72, name: 'Seltzer', humanoid: false, bg: '#bfdbfe', notes: 'Seltzer bottle' },
  { id: 73, name: 'Castle', humanoid: false, bg: '#475569', notes: 'Castle' },
  {
    id: 74,
    name: 'Smiley Face',
    humanoid: true,
    bg: '#fbbf24',
    notes: 'Classic smiley — is a face',
  },
  { id: 75, name: 'Campfire', humanoid: false, bg: '#b45309', notes: 'Campfire' },
  { id: 76, name: 'Golden Joker', humanoid: false, bg: '#b45309', notes: 'Gold abstract card' },
  { id: 77, name: 'Popcorn', humanoid: false, bg: '#fef9c3', notes: 'Popcorn box' },
  { id: 78, name: 'Acrobat', humanoid: true, bg: '#7c2d12', notes: 'Acrobat character' },
  {
    id: 79,
    name: 'Sock and Buskin',
    humanoid: true,
    bg: '#1c1917',
    notes: 'Comedy/tragedy masks — faces',
  },
  { id: 80, name: 'Swashbuckler', humanoid: true, bg: '#b45309', notes: 'Swashbuckler character' },
  { id: 81, name: 'Troubadour', humanoid: true, bg: '#451a03', notes: 'Medieval troubadour' },
  { id: 82, name: 'Certificate', humanoid: true, bg: '#fffbeb', notes: 'Face on a certificate' },
  { id: 83, name: 'Smeared Joker', humanoid: true, bg: '#be123c', notes: 'Smeared paint Jimbo' },
  { id: 84, name: 'Showman', humanoid: true, bg: '#7f1d1d', notes: 'Top hat showman' },
  { id: 85, name: 'Flower Pot', humanoid: false, bg: '#92400e', notes: 'Flower pot, no face' },
  { id: 86, name: 'Blueprint', humanoid: false, bg: '#1e3a5f', notes: 'Technical blueprint' },
  { id: 87, name: 'Cavendish', humanoid: false, bg: '#fde047', notes: 'Banana' },
  { id: 88, name: 'Erosion', humanoid: false, bg: '#92400e', notes: 'Eroding cliff' },
  { id: 89, name: 'Reserved Parking', humanoid: false, bg: '#1e3a5f', notes: 'Parking sign' },
  { id: 90, name: 'Mail-In Rebate', humanoid: false, bg: '#f5f5f4', notes: 'Rebate form' },
  { id: 91, name: 'To the Moon', humanoid: false, bg: '#0f172a', notes: 'Moon' },
  { id: 92, name: 'Hallucination', humanoid: false, bg: '#7c3aed', notes: 'Psychedelic pattern' },
  { id: 93, name: 'Juggler', humanoid: true, bg: '#b45309', notes: 'Juggling character' },
  { id: 94, name: 'Drunkard', humanoid: true, bg: '#7f1d1d', notes: 'Drunk, red nose' },
  { id: 95, name: 'Stone Joker', humanoid: false, bg: '#374151', notes: 'Stone texture' },
  {
    id: 96,
    name: 'Baseball Card',
    humanoid: true,
    bg: '#dbeafe',
    notes: 'Joker playing baseball — has a face lol',
  },
  { id: 97, name: 'Constellation', humanoid: false, bg: '#0f172a', notes: 'Star constellation' },
  { id: 98, name: 'Arrowhead', humanoid: false, bg: '#78350f', notes: 'Arrowhead' },
  { id: 99, name: 'Onyx Agate', humanoid: false, bg: '#111827', notes: 'Gem' },
  { id: 100, name: 'Glass Joker', humanoid: false, bg: '#bfdbfe', notes: 'Glass/crystal' },
  { id: 101, name: 'Rough Gem', humanoid: false, bg: '#065f46', notes: 'Rough gem' },
  { id: 102, name: 'Bloodstone', humanoid: false, bg: '#7f1d1d', notes: 'Bloodstone gem' },
  { id: 103, name: 'Hiker', humanoid: true, bg: '#15803d', notes: 'Hiker with backpack' },
  { id: 104, name: 'Green Joker', humanoid: false, bg: '#16a34a', notes: 'Abstract green card' },
  {
    id: 105,
    name: 'Superposition',
    humanoid: false,
    bg: '#312e81',
    notes: 'Quantum superposition',
  },
  { id: 106, name: 'To Do List', humanoid: false, bg: '#f5f5f4', notes: 'Checklist' },
  {
    id: 107,
    name: 'Faceless Joker',
    humanoid: true,
    bg: '#374151',
    notes: 'INTENTIONALLY no face — blank head',
  },
  { id: 108, name: 'Shoot the Moon', humanoid: false, bg: '#0f172a', notes: 'Moon shot, no face' },
  { id: 109, name: 'Bootstraps', humanoid: false, bg: '#78350f', notes: 'Boots only' },
  { id: 110, name: 'Vampire', humanoid: true, bg: '#1a0a0a', notes: 'Vampire character' },
  { id: 111, name: 'Shortcut', humanoid: false, bg: '#16a34a', notes: 'Shortcut symbol' },
  { id: 112, name: 'Hologram', humanoid: false, bg: '#7c3aed', notes: 'Hologram card' },
  { id: 113, name: 'Sixth Sense', humanoid: true, bg: '#4c1d95', notes: 'Psychic third eye face' },
  { id: 114, name: 'Séance', humanoid: true, bg: '#0c0a09', notes: 'Ghost/spirit face' },
  { id: 115, name: 'Riff-Raff', humanoid: true, bg: '#7c3aed', notes: 'Riff-raff character' },
  { id: 116, name: 'Satellite', humanoid: false, bg: '#0f172a', notes: 'Satellite dish' },
  { id: 117, name: 'Hit the Road', humanoid: true, bg: '#1c1917', notes: 'Driver leaving town' },
  { id: 118, name: 'The Duo', humanoid: true, bg: '#7c3aed', notes: 'Two faces' },
  { id: 119, name: 'The Trio', humanoid: true, bg: '#16a34a', notes: 'Three faces' },
  { id: 120, name: 'The Family', humanoid: true, bg: '#b45309', notes: 'Family of faces' },
  { id: 121, name: 'The Order', humanoid: true, bg: '#1e3a5f', notes: 'Order/knight face' },
  { id: 122, name: 'The Tribe', humanoid: true, bg: '#78350f', notes: 'Tribal face' },
  { id: 123, name: 'Stuntman', humanoid: true, bg: '#b45309', notes: 'Stuntman character' },
  {
    id: 124,
    name: 'Invisible Joker',
    humanoid: true,
    bg: '#e5e7eb',
    notes: 'Invisible — blank transparent body',
  },
  { id: 125, name: 'Brainstorm', humanoid: true, bg: '#7c3aed', notes: 'Brain/thinking character' },
  {
    id: 126,
    name: "Driver's License",
    humanoid: true,
    bg: '#fef9c3',
    notes: 'ID card with face photo',
  },
  { id: 127, name: 'Burnt Joker', humanoid: true, bg: '#1c1917', notes: 'Charred Jimbo face' },
  { id: 128, name: 'Obelisk', humanoid: false, bg: '#374151', notes: 'Stone monolith' },
  { id: 129, name: 'Blue Joker', humanoid: false, bg: '#1d4ed8', notes: 'Abstract blue card' },
  { id: 130, name: 'Gift Card', humanoid: false, bg: '#fbbf24', notes: 'Gift card' },
  { id: 131, name: 'Turtle Bean', humanoid: false, bg: '#166534', notes: 'Turtle bean' },
  { id: 132, name: 'Erosion', humanoid: false, bg: '#92400e', notes: 'duplicate — check wiki' },
  { id: 133, name: 'Matador', humanoid: true, bg: '#dc2626', notes: 'Matador bullfighter' },
  {
    id: 134,
    name: 'Cartomancer',
    humanoid: true,
    bg: '#2e1065',
    notes: 'Fortune teller character',
  },
  { id: 135, name: 'Astronomer', humanoid: true, bg: '#0f172a', notes: 'Astronomer character' },
  { id: 136, name: 'Throwback', humanoid: false, bg: '#374151', notes: 'Abstract card' },
  { id: 137, name: 'Runner', humanoid: true, bg: '#16a34a', notes: 'Running character' },
  { id: 138, name: 'Vampire', humanoid: true, bg: '#1a0a0a', notes: 'duplicate — check wiki' },
  {
    id: 139,
    name: 'Square Joker',
    humanoid: false,
    bg: '#374151',
    notes: 'Literally a square card',
  },
  { id: 140, name: 'Splash', humanoid: false, bg: '#bfdbfe', notes: 'Water splash' },
  { id: 141, name: 'Midas Mask', humanoid: true, bg: '#b45309', notes: 'Gold mask — is a face' },
  {
    id: 142,
    name: 'Luchador',
    humanoid: true,
    bg: '#dc2626',
    notes: 'Luchador mask — iconic face',
  },
  { id: 143, name: 'Photograph', humanoid: true, bg: '#f5f5f4', notes: 'duplicate — check wiki' },
  { id: 144, name: 'Gift Card', humanoid: false, bg: '#fbbf24', notes: 'duplicate — check wiki' },
  { id: 145, name: 'Canio', humanoid: true, bg: '#fef3c7', notes: 'Pagliacci opera clown' },
  { id: 146, name: 'Triboulet', humanoid: true, bg: '#1e3a5f', notes: 'Royal jester' },
  { id: 147, name: 'Yorick', humanoid: true, bg: '#1c1917', notes: 'Skull — Yorick from Hamlet' },
  { id: 148, name: 'Chicot', humanoid: true, bg: '#7f1d1d', notes: 'Historical royal jester' },
  { id: 149, name: 'Perkeo', humanoid: true, bg: '#7c3aed', notes: 'Dwarf jester Perkeo' },
]

export function dedupeJokersByName(rows: JokerRow[]): JokerRow[] {
  const seen = new Set<string>()
  return rows.filter((j) => {
    if (seen.has(j.name)) return false
    seen.add(j.name)
    return true
  })
}

export const BASE_JOKERS = dedupeJokersByName(DEFAULT_JOKERS)

const STORAGE_KEY = 'balatro-jokers'

export function loadJokersFromStorage(): JokerRow[] | null {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (!raw) return null
    const parsed = JSON.parse(raw) as unknown
    if (!Array.isArray(parsed)) return null
    return parsed as JokerRow[]
  } catch {
    return null
  }
}

export function saveJokersToStorage(rows: JokerRow[]): void {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(rows))
}
