/**
 * Generates tools/jaml-language/monaco/src/index.ts from the JAML schema.
 * Run after schema changes: node tools/jaml-language/gen-monaco.mjs
 */
import { readFileSync, writeFileSync } from "fs";

const schema = JSON.parse(readFileSync("jaml.schema.json", "utf8"));
const c = schema.definitions.clause.properties;
const col = (p) => p?.enum ?? p?.items?.enum ?? [];

const SPECIAL = {
  EightBall: "8 Ball", Cloud9: "Cloud 9", OopsAll6s: "Oops! All 6s",
  ToTheMoon: "To the Moon", ToDoList: "To Do List", RiffRaff: "Riff-raff",
  MailInRebate: "Mail In Rebate", SockAndBuskin: "Sock and Buskin",
  DriversLicense: "Driver's License", DirectorsCut: "Director's Cut",
  PlanetX: "Planet X", MrBones: "Mr. Bones", ChaostheClown: "Chaos the Clown",
  ShootTheMoon: "Shoot the Moon", RideTheBus: "Ride the Bus",
  HitTheRoad: "Hit the Road", VerdantLeaf: "Verdant Leaf",
  GrosMichel: "Gros Michel",
};
function displayName(n) {
  if (SPECIAL[n]) return SPECIAL[n];
  return n.replace(/([A-Z])/g, (m, c, i) => (i > 0 ? " " : "") + c).trim();
}
function namesFor(arr) {
  const all = new Set(arr);
  for (const v of arr) { const d = displayName(v); if (d !== v) all.add(d); }
  return [...all];
}
function escRe(arr) {
  return arr.map(v => v.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
            .sort((a, b) => b.length - a.length)  // longest first → greedy match
            .join("|");
}

const jokers    = namesFor(col(c.joker).filter(v => !["any","anycommon","anyuncommon","anyrare","anylegendary"].includes(v)));
const wildcards = ["any", "anycommon", "anyuncommon", "anyrare", "anylegendary"];
const vouchers  = namesFor(col(c.voucher));
const bosses    = namesFor(col(c.boss));
const tags      = namesFor(col(c.tag));
const tarots    = namesFor(col(c.tarotCard));
const spectrals = namesFor(col(c.spectralCard));
const planets   = namesFor(col(c.planetCard));
const decks     = schema.properties.deck.enum;
const stakes    = schema.properties.stake.enum;
const editions  = namesFor(col(c.edition));
const modifiers = namesFor([...c.stickers.items.enum, ...col(c.seal), ...col(c.enhancement)]);
const aesthetics = schema.definitions.JamlAesthetic.enum;

const out = `// AUTO-GENERATED by tools/jaml-language/gen-monaco.mjs — do not edit by hand.
export function registerJamlLanguage(monaco: any): void {
  monaco.languages.register({ id: "jaml" });
  monaco.languages.register({ id: "jummy" });

  const tokenizer = {
    root: [
      [/^\\s*#.*$/, "comment"],
      [/^(\\s*)([A-Za-z_][\\w-]*)(\\s*:)/, ["", "key", ""]],
      [/\\b(true|false|null)\\b/, "keyword"],
      [/\\b-?\\d+(?:\\.\\d+)?\\b/, "number"],
      [/\\b(${escRe(wildcards)})\\b/, "keyword"],
      [/\\b(${escRe([...decks, ...stakes])})\\b/, "type"],
      [/\\b(${escRe(aesthetics)})\\b/, "keyword"],
      [/"(${escRe(wildcards)})"/, "keyword"],
      [/'(${escRe(wildcards)})'/, "keyword"],
      [/"(${escRe([...decks, ...stakes])})"/, "type"],
      [/'(${escRe([...decks, ...stakes])})'/, "type"],
      [/"(${escRe(aesthetics)})"/, "keyword"],
      [/'(${escRe(aesthetics)})'/, "keyword"],
      [/(${escRe(jokers)})/, "function"],
      [/"(${escRe(jokers)})"/, "function"],
      [/'(${escRe(jokers)})'/, "function"],
      [/(${escRe(vouchers)})/, "variable"],
      [/"(${escRe(vouchers)})"/, "variable"],
      [/'(${escRe(vouchers)})'/, "variable"],
      [/(${escRe(bosses)})/, "type.identifier"],
      [/"(${escRe(bosses)})"/, "type.identifier"],
      [/'(${escRe(bosses)})'/, "type.identifier"],
      [/(${escRe(tags)})/, "variable.predefined"],
      [/"(${escRe(tags)})"/, "variable.predefined"],
      [/'(${escRe(tags)})'/, "variable.predefined"],
      [/(${escRe(tarots)})/, "string"],
      [/"(${escRe(tarots)})"/, "string"],
      [/'(${escRe(tarots)})'/, "string"],
      [/(${escRe(spectrals)})/, "string"],
      [/"(${escRe(spectrals)})"/, "string"],
      [/'(${escRe(spectrals)})'/, "string"],
      [/(${escRe(planets)})/, "string"],
      [/"(${escRe(planets)})"/, "string"],
      [/'(${escRe(planets)})'/, "string"],
      [/\\b(${escRe(editions)})\\b/, "emphasis"],
      [/"(${escRe(editions)})"/, "emphasis"],
      [/'(${escRe(editions)})'/, "emphasis"],
      [/\\b(${escRe(modifiers)})\\b/, "strong"],
      [/"(${escRe(modifiers)})"/, "strong"],
      [/'(${escRe(modifiers)})'/, "strong"],
      [/"([^"\\\\]|\\\\.)*"/, "string"],
      [/'([^'\\\\]|\\\\.)*'/, "string"],
    ],
  };

  monaco.languages.setMonarchTokensProvider("jaml",   { tokenizer });
  monaco.languages.setMonarchTokensProvider("jummy",  { tokenizer });

  const langConfig = {
    comments: { lineComment: "#" },
    brackets: [["{", "}"], ["[", "]"]],
    autoClosingPairs: [
      { open: "{", close: "}" },
      { open: "[", close: "]" },
      { open: '"', close: '"' },
    ],
  };
  monaco.languages.setLanguageConfiguration("jaml",  langConfig);
  monaco.languages.setLanguageConfiguration("jummy", langConfig);
}
`;

writeFileSync("tools/jaml-language/monaco/src/index.ts", out);
console.log("Written: tools/jaml-language/monaco/src/index.ts");
