// AUTO-GENERATED by Motely.Schema.cs — DO NOT EDIT.
// Source of truth: the real clause/source-config C# types, via
// Motely/Filters/Jaml/JamlDiscriminatorRegistry.cs + enum reflection.

export const Enums: Record<string, readonly string[]> = {
    MotelyBossBlind: ["TheClub", "TheGoad", "TheHead", "TheHook", "TheManacle", "ThePillar", "ThePsychic", "TheWindow", "TheArm", "TheFish", "TheFlint", "TheHouse", "TheMark", "TheMouth", "TheNeedle", "TheWall", "TheWater", "TheWheel", "TheEye", "TheTooth", "ThePlant", "TheSerpent", "TheOx", "AmberAcorn", "CeruleanBell", "CrimsonHeart", "VerdantLeaf", "VioletVessel"],
    MotelyItemEdition: ["None", "Foil", "Holographic", "Polychrome", "Negative"],
    MotelyItemEnhancement: ["None", "Bonus", "Mult", "Wild", "Glass", "Steel", "Stone", "Gold", "Lucky"],
    MotelyItemSeal: ["None", "Gold", "Red", "Blue", "Purple"],
    MotelyJoker: ["Joker", "GreedyJoker", "LustyJoker", "WrathfulJoker", "GluttonousJoker", "JollyJoker", "ZanyJoker", "MadJoker", "CrazyJoker", "DrollJoker", "SlyJoker", "WilyJoker", "CleverJoker", "DeviousJoker", "CraftyJoker", "HalfJoker", "CreditCard", "Banner", "MysticSummit", "EightBall", "Misprint", "RaisedFist", "ChaostheClown", "ScaryFace", "AbstractJoker", "DelayedGratification", "GrosMichel", "EvenSteven", "OddTodd", "Scholar", "BusinessCard", "Supernova", "RideTheBus", "Egg", "Runner", "IceCream", "Splash", "BlueJoker", "FacelessJoker", "GreenJoker", "Superposition", "ToDoList", "Cavendish", "RedCard", "SquareJoker", "RiffRaff", "Photograph", "ReservedParking", "MailInRebate", "Hallucination", "FortuneTeller", "Juggler", "Drunkard", "GoldenJoker", "Popcorn", "WalkieTalkie", "SmileyFace", "GoldenTicket", "Swashbuckler", "HangingChad", "ShootTheMoon", "JokerStencil", "FourFingers", "Mime", "CeremonialDagger", "MarbleJoker", "LoyaltyCard", "Dusk", "Fibonacci", "SteelJoker", "Hack", "Pareidolia", "SpaceJoker", "Burglar", "Blackboard", "SixthSense", "Constellation", "Hiker", "CardSharp", "Madness", "Seance", "Vampire", "Shortcut", "Hologram", "Cloud9", "Rocket", "MidasMask", "Luchador", "GiftCard", "TurtleBean", "Erosion", "ToTheMoon", "StoneJoker", "LuckyCat", "Bull", "DietCola", "TradingCard", "FlashCard", "SpareTrousers", "Ramen", "Seltzer", "Castle", "MrBones", "Acrobat", "SockAndBuskin", "Troubadour", "Certificate", "SmearedJoker", "Throwback", "RoughGem", "Bloodstone", "Arrowhead", "OnyxAgate", "GlassJoker", "Showman", "FlowerPot", "MerryAndy", "OopsAll6s", "TheIdol", "SeeingDouble", "Matador", "Satellite", "Cartomancer", "Astronomer", "Bootstraps", "DNA", "Vagabond", "Baron", "Obelisk", "BaseballCard", "AncientJoker", "Campfire", "Blueprint", "WeeJoker", "HitTheRoad", "TheDuo", "TheTrio", "TheFamily", "TheOrder", "TheTribe", "Stuntman", "InvisibleJoker", "Brainstorm", "DriversLicense", "BurntJoker", "Canio", "Triboulet", "Yorick", "Chicot", "Perkeo"],
    MotelyJokerCommon: ["Joker", "GreedyJoker", "LustyJoker", "WrathfulJoker", "GluttonousJoker", "JollyJoker", "ZanyJoker", "MadJoker", "CrazyJoker", "DrollJoker", "SlyJoker", "WilyJoker", "CleverJoker", "DeviousJoker", "CraftyJoker", "HalfJoker", "CreditCard", "Banner", "MysticSummit", "EightBall", "Misprint", "RaisedFist", "ChaostheClown", "ScaryFace", "AbstractJoker", "DelayedGratification", "GrosMichel", "EvenSteven", "OddTodd", "Scholar", "BusinessCard", "Supernova", "RideTheBus", "Egg", "Runner", "IceCream", "Splash", "BlueJoker", "FacelessJoker", "GreenJoker", "Superposition", "ToDoList", "Cavendish", "RedCard", "SquareJoker", "RiffRaff", "Photograph", "ReservedParking", "MailInRebate", "Hallucination", "FortuneTeller", "Juggler", "Drunkard", "GoldenJoker", "Popcorn", "WalkieTalkie", "SmileyFace", "GoldenTicket", "Swashbuckler", "HangingChad", "ShootTheMoon"],
    MotelyJokerRare: ["DNA", "Vagabond", "Baron", "Obelisk", "BaseballCard", "AncientJoker", "Campfire", "Blueprint", "WeeJoker", "HitTheRoad", "TheDuo", "TheTrio", "TheFamily", "TheOrder", "TheTribe", "Stuntman", "InvisibleJoker", "Brainstorm", "DriversLicense", "BurntJoker"],
    MotelyJokerSticker: ["None", "Eternal", "Perishable", "Rental"],
    MotelyJokerUncommon: ["JokerStencil", "FourFingers", "Mime", "CeremonialDagger", "MarbleJoker", "LoyaltyCard", "Dusk", "Fibonacci", "SteelJoker", "Hack", "Pareidolia", "SpaceJoker", "Burglar", "Blackboard", "SixthSense", "Constellation", "Hiker", "CardSharp", "Madness", "Seance", "Vampire", "Shortcut", "Hologram", "Cloud9", "Rocket", "MidasMask", "Luchador", "GiftCard", "TurtleBean", "Erosion", "ToTheMoon", "StoneJoker", "LuckyCat", "Bull", "DietCola", "TradingCard", "FlashCard", "SpareTrousers", "Ramen", "Seltzer", "Castle", "MrBones", "Acrobat", "SockAndBuskin", "Troubadour", "Certificate", "SmearedJoker", "Throwback", "RoughGem", "Bloodstone", "Arrowhead", "OnyxAgate", "GlassJoker", "Showman", "FlowerPot", "MerryAndy", "OopsAll6s", "TheIdol", "SeeingDouble", "Matador", "Satellite", "Cartomancer", "Astronomer", "Bootstraps"],
    MotelyPlanetCard: ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto", "PlanetX", "Ceres", "Eris"],
    MotelySpectralCard: ["Familiar", "Grim", "Incantation", "Talisman", "Aura", "Wraith", "Sigil", "Ouija", "Ectoplasm", "Immolate", "Ankh", "DejaVu", "Hex", "Trance", "Medium", "Cryptid", "TheSoul", "BlackHole"],
    MotelyStandardcardRank: ["Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Jack", "Queen", "King", "Ace"],
    MotelyStandardcardSuit: ["Clubs", "Diamonds", "Hearts", "Spades"],
    MotelyTag: ["UncommonTag", "RareTag", "NegativeTag", "FoilTag", "HolographicTag", "PolychromeTag", "InvestmentTag", "VoucherTag", "BossTag", "StandardTag", "CharmTag", "MeteorTag", "BuffoonTag", "HandyTag", "GarbageTag", "EtherealTag", "CouponTag", "DoubleTag", "JuggleTag", "D6Tag", "TopupTag", "SpeedTag", "OrbitalTag", "EconomyTag"],
    MotelyTarotCard: ["TheFool", "TheMagician", "TheHighPriestess", "TheEmpress", "TheEmperor", "TheHierophant", "TheLovers", "TheChariot", "Justice", "TheHermit", "TheWheelOfFortune", "Strength", "TheHangedMan", "Death", "Temperance", "TheDevil", "TheTower", "TheStar", "TheMoon", "TheSun", "Judgement", "TheWorld"],
    MotelyVoucher: ["Overstock", "OverstockPlus", "ClearanceSale", "Liquidation", "Hone", "GlowUp", "RerollSurplus", "RerollGlut", "CrystalBall", "OmenGlobe", "Telescope", "Observatory", "Grabber", "NachoTong", "Wasteful", "Recyclomancy", "TarotMerchant", "TarotTycoon", "PlanetMerchant", "PlanetTycoon", "SeedMoney", "MoneyTree", "Blank", "Antimatter", "MagicTrick", "Illusion", "Hieroglyph", "Petroglyph", "DirectorsCut", "Retcon", "PaintBrush", "Palette"],
};

export const Discriminators: readonly string[] = ["and", "bigBlindTag", "bloodstoneTrigger", "boss", "businessPayout", "cavendishExtinct", "commonJoker", "commonJokers", "erraticRank", "erraticRanks", "erraticSuit", "glassDestroy", "grosMichelExtinct", "joker", "jokers", "legendaryJoker", "legendaryJokers", "luckyMoney", "luckyMult", "misprintMult", "or", "parkingPayout", "planetCard", "rareJoker", "rareJokers", "smallBlindTag", "spaceLevelup", "spectralCard", "standardCard", "startingDraw", "tag", "tarotCard", "uncommonJoker", "uncommonJokers", "voucher", "wheelOfFortune", "wheelStaysFlipped"];
export const RootKeys: readonly string[] = ["author", "dateCreated", "deck", "description", "id", "must", "mustNot", "name", "seeds", "should", "stake"];
export const AllClauseLevelKeys: readonly string[] = ["ante", "antes", "boosterPacks", "clauses", "edition", "enhancement", "label", "luck", "max", "min", "mult", "rank", "rolls", "score", "seal", "shopItems", "soulCardOnly", "soulEditionRolls", "sources", "stickers", "suit", "value", "vouchers", "with"];

export const RootValueEnums: Record<string, string> = { deck: "MotelyDeck", stake: "MotelyStake" };

export const DiscriminatorValueEnum: Record<string, string> = {
    "bigBlindTag": "MotelyTag",
    "boss": "MotelyBossBlind",
    "commonJoker": "MotelyJokerCommon",
    "commonJokers": "MotelyJokerCommon",
    "erraticRank": "MotelyStandardcardRank",
    "erraticRanks": "MotelyStandardcardRank",
    "erraticSuit": "MotelyStandardcardSuit",
    "joker": "MotelyJoker",
    "jokers": "MotelyJoker",
    "legendaryJoker": "MotelyJoker",
    "legendaryJokers": "MotelyJoker",
    "planetCard": "MotelyPlanetCard",
    "rareJoker": "MotelyJokerRare",
    "rareJokers": "MotelyJokerRare",
    "smallBlindTag": "MotelyTag",
    "spectralCard": "MotelySpectralCard",
    "tag": "MotelyTag",
    "tarotCard": "MotelyTarotCard",
    "uncommonJoker": "MotelyJokerUncommon",
    "uncommonJokers": "MotelyJokerUncommon",
    "voucher": "MotelyVoucher",
};

export const ClauseKeyValueEnum: Record<string, string> = {
    "edition": "MotelyItemEdition",
    "enhancement": "MotelyItemEnhancement",
    "rank": "MotelyStandardcardRank",
    "seal": "MotelyItemSeal",
    "stickers": "MotelyJokerSticker",
    "suit": "MotelyStandardcardSuit",
};

export const DiscriminatorClauseKeys: Record<string, readonly string[]> = {
    "and": ["clauses", "ante", "antes"],
    "bigBlindTag": ["rolls"],
    "bloodstoneTrigger": [],
    "boss": [],
    "businessPayout": [],
    "cavendishExtinct": ["with"],
    "commonJoker": ["edition", "stickers", "shopItems", "boosterPacks"],
    "commonJokers": ["edition", "stickers", "shopItems", "boosterPacks"],
    "erraticRank": [],
    "erraticRanks": [],
    "erraticSuit": [],
    "glassDestroy": ["with"],
    "grosMichelExtinct": ["with"],
    "joker": ["edition", "stickers", "shopItems", "boosterPacks"],
    "jokers": ["edition", "stickers", "shopItems", "boosterPacks"],
    "legendaryJoker": ["edition", "soulCardOnly", "soulEditionRolls", "boosterPacks"],
    "legendaryJokers": ["edition", "soulCardOnly", "soulEditionRolls", "boosterPacks"],
    "luckyMoney": ["with"],
    "luckyMult": ["with"],
    "misprintMult": ["mult", "value"],
    "or": ["clauses", "ante", "antes"],
    "parkingPayout": [],
    "planetCard": ["shopItems", "boosterPacks"],
    "rareJoker": ["edition", "stickers", "shopItems", "boosterPacks"],
    "rareJokers": ["edition", "stickers", "shopItems", "boosterPacks"],
    "smallBlindTag": ["rolls"],
    "spaceLevelup": ["with"],
    "spectralCard": ["shopItems", "boosterPacks"],
    "standardCard": ["rank", "suit", "enhancement", "seal", "edition", "shopItems", "boosterPacks"],
    "startingDraw": ["rank", "suit"],
    "tag": ["rolls"],
    "tarotCard": ["shopItems", "boosterPacks"],
    "uncommonJoker": ["edition", "stickers", "shopItems", "boosterPacks"],
    "uncommonJokers": ["edition", "stickers", "shopItems", "boosterPacks"],
    "voucher": ["rolls"],
    "wheelOfFortune": ["with"],
    "wheelStaysFlipped": ["with"],
};

export const DiscriminatorSourceKeys: Record<string, readonly string[]> = {
    "commonJoker": ["shopItems", "boosterPacks", "judgement", "wraith", "riffRaff", "rareTag", "uncommonTag", "commonShopJokers", "uncommonShopJokers", "rareShopJokers", "allShopJokers"],
    "commonJokers": ["shopItems", "boosterPacks", "judgement", "wraith", "riffRaff", "rareTag", "uncommonTag", "commonShopJokers", "uncommonShopJokers", "rareShopJokers", "allShopJokers"],
    "joker": ["shopItems", "boosterPacks", "judgement", "wraith", "riffRaff", "rareTag", "uncommonTag", "commonShopJokers", "uncommonShopJokers", "rareShopJokers", "allShopJokers"],
    "jokers": ["shopItems", "boosterPacks", "judgement", "wraith", "riffRaff", "rareTag", "uncommonTag", "commonShopJokers", "uncommonShopJokers", "rareShopJokers", "allShopJokers"],
    "legendaryJoker": ["boosterPacks", "arcanaPacks", "spectralPacks", "soulCard", "requireMega", "requireMegaPack"],
    "legendaryJokers": ["boosterPacks", "arcanaPacks", "spectralPacks", "soulCard", "requireMega", "requireMegaPack"],
    "planetCard": ["shopItems", "boosterPacks"],
    "rareJoker": ["shopItems", "boosterPacks", "judgement", "wraith", "riffRaff", "rareTag", "uncommonTag", "commonShopJokers", "uncommonShopJokers", "rareShopJokers", "allShopJokers"],
    "rareJokers": ["shopItems", "boosterPacks", "judgement", "wraith", "riffRaff", "rareTag", "uncommonTag", "commonShopJokers", "uncommonShopJokers", "rareShopJokers", "allShopJokers"],
    "spectralCard": ["shopItems", "boosterPacks", "sixthSense", "seance", "etherealTag", "requireMega", "requireMegaPack"],
    "standardCard": ["shopItems", "boosterPacks", "certificate", "incantation", "familiar", "grim", "deckDraw"],
    "tarotCard": ["shopItems", "boosterPacks", "emperor", "purpleSealOrEightBall", "charmTag"],
    "uncommonJoker": ["shopItems", "boosterPacks", "judgement", "wraith", "riffRaff", "rareTag", "uncommonTag", "commonShopJokers", "uncommonShopJokers", "rareShopJokers", "allShopJokers"],
    "uncommonJokers": ["shopItems", "boosterPacks", "judgement", "wraith", "riffRaff", "rareTag", "uncommonTag", "commonShopJokers", "uncommonShopJokers", "rareShopJokers", "allShopJokers"],
};
