// AUTO-GENERATED by codegen/gen-streams.mjs — DO NOT EDIT BY HAND.
// Source of truth: Motely/MotelySingleSearchContext.*.cs
// Regenerate: node codegen/gen-streams.mjs

export interface EngineStream {
  /** The Create*Stream factory on MotelySingleSearchContext. */
  readonly name: string;
  /** The stream struct it returns. */
  readonly returns: string;
  /** Partial-class suffix: Boss, Jokers, Tarot, Spectral, Planet, Misc, ... */
  readonly category: string;
}

export const ENGINE_STREAMS = [
  { name: "CreateBossStream", returns: "MotelySingleBossStream", category: "Boss" },
  { name: "CreateBuffoonPackJokerStream", returns: "MotelySingleJokerStream", category: "Jokers" },
  { name: "CreateCommonShopJokerStream", returns: "MotelySingleJokerFixedRarityStream", category: "Jokers" },
  { name: "CreateJudgementJokerStream", returns: "MotelySingleJokerStream", category: "Jokers" },
  { name: "CreateLegendaryJokerStream", returns: "MotelySingleJokerFixedRarityStream", category: "Jokers" },
  { name: "CreateRareShopJokerStream", returns: "MotelySingleJokerFixedRarityStream", category: "Jokers" },
  { name: "CreateRareTagJokerStream", returns: "MotelySingleJokerFixedRarityStream", category: "Jokers" },
  { name: "CreateRiffRaffJokerStream", returns: "MotelySingleJokerFixedRarityStream", category: "Jokers" },
  { name: "CreateShopJokerStream", returns: "MotelySingleJokerStream", category: "Jokers" },
  { name: "CreateUncommonShopJokerStream", returns: "MotelySingleJokerFixedRarityStream", category: "Jokers" },
  { name: "CreateUncommonTagJokerStream", returns: "MotelySingleJokerFixedRarityStream", category: "Jokers" },
  { name: "CreateWraithJokerStream", returns: "MotelySingleJokerStream", category: "Jokers" },
  { name: "CreateBloodstonePrngStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateBusinessPrngStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateCavendishPrngStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateEightBallPrngStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateErraticDeckPrngStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateGlassPrngStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateGrosMichelPrngStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateLuckyCardMoneyStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateLuckyCardMultStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateMisprintPrngStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateOmenGlobePrngStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateParkingPrngStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateSpacePrngStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateTheWheelPrngStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateWheelOfFortuneStream", returns: "MotelySinglePrngStream", category: "Misc" },
  { name: "CreateBoosterPackStream", returns: "MotelySingleBoosterPackStream", category: "Packs" },
  { name: "CreateCelestialPackPlanetStream", returns: "MotelySinglePlanetStream", category: "Planet" },
  { name: "CreateShopPlanetStream", returns: "MotelySinglePlanetStream", category: "Planet" },
  { name: "CreateShopItemStream", returns: "MotelySingleShopItemStream", category: "Shop" },
  { name: "CreateSeanceSpectralStream", returns: "MotelySingleSpectralStream", category: "Spectral" },
  { name: "CreateShopSpectralStream", returns: "MotelySingleSpectralStream", category: "Spectral" },
  { name: "CreateSixthSenseSpectralStream", returns: "MotelySingleSpectralStream", category: "Spectral" },
  { name: "CreateSpectralPackSpectralStream", returns: "MotelySingleSpectralStream", category: "Spectral" },
  { name: "CreateStandardPackCardStream", returns: "MotelySingleStandardCardStream", category: "StandardCards" },
  { name: "CreateTagStream", returns: "MotelySingleTagStream", category: "Tags" },
  { name: "CreateArcanaPackTarotStream", returns: "MotelySingleTarotStream", category: "Tarot" },
  { name: "CreateEmperorTarotStream", returns: "MotelySingleTarotStream", category: "Tarot" },
  { name: "CreatePurpleSealTarotStream", returns: "MotelySingleTarotStream", category: "Tarot" },
  { name: "CreateShopTarotStream", returns: "MotelySingleTarotStream", category: "Tarot" },
  { name: "CreateVoucherStream", returns: "MotelySingleVoucherStream", category: "Vouchers" },
] as const satisfies readonly EngineStream[];

export type EngineStreamName = (typeof ENGINE_STREAMS)[number]["name"];
