using YamlDotNet.Serialization;

namespace Motely.Filters;

/// <summary>
/// YamlDotNet static deserialization context (source-generated by Vecc.YamlDotNet.Analyzers.StaticGenerator).
/// Required for Native AOT, LLVM WASM, and aggressive trimming — avoids reflection in <see cref="DeserializerBuilder"/>.
/// </summary>
[YamlStaticContext]
[YamlSerializable(typeof(JamlRootDocument))]
[YamlSerializable(typeof(JamlDefaults))]
[YamlSerializable(typeof(JamlClauseUnion))]
[YamlSerializable(typeof(JamlSources))]
public sealed partial class JamlYamlContext : StaticContext;
