import bootsharp, {
    MotelyJaml,
    MotelySearch,
    MotelyJamlyzer,
    MotelyUtilities,
    Jimmolate,
    JamlAesthetic,
} from "motely-wasm";
import type { JamlConfig, MotelyJamlyzerSeedResult } from "motely-wasm";

export type MotelyRuntimeStatus = "idle" | "booting" | "ready" | "error";

// ── motely-wasm@23 ──
// The old `Program` namespace (parseJaml / run*Search / jamlyzer / the file-system
// ops) was removed. v23 splits the surface into top-level namespaces — MotelyJaml,
// MotelySearch, MotelyJamlyzer, MotelyUtilities, Jimmolate — re-exported from the
// single package root. The thin adapters below sit on those real exports so the
// rest of jaml-ui keeps one engine entry point.

// ── Parse / validate ──
// v23 replaced `Program.parseJaml` (parse-or-throw) with MotelyJaml.validate
// (returns an error string, or null when valid) + MotelyJaml.fromYaml (the parse).
// Preserve the parse-or-throw contract every caller relies on.
export function parseJaml(jaml: string): JamlConfig {
    const error = MotelyJaml.validate(jaml);
    if (error) throw new Error(error);
    return MotelyJaml.fromYaml(jaml);
}

/** Column labels for a parsed filter's score tallies (was `MotelyJamlyzerResult.tallyLabels`). */
export function tallyLabelsFor(config: JamlConfig): string[] {
    return MotelyJaml.createPlan(config).tallyLabels ?? [];
}

// ── Jimmolate probe ──
// v23 exposes `Jimmolate.findSeed` (a settable predicate) + `Jimmolate.enabled`.
// findSeed is a Bootsharp [Import]: it must be assigned BEFORE boot() or the C#
// side calls an unbound import. So bind a stable dispatcher at module load (this
// runs on import, always before any ensureMotelyReady()/boot()) and swap the inner
// predicate per search via setJimmolateProbe().
type JimmolateProbe = (seed: string, deck: number, stake: number) => boolean;
let currentProbe: JimmolateProbe = () => true;
Jimmolate.findSeed = (seed: string, deck: number, stake: number) => currentProbe(seed, deck, stake);

/** Swap the active Jimmolate predicate. Safe before or after boot. */
export function setJimmolateProbe(pred: JimmolateProbe): void {
    currentProbe = pred;
}

/** Reset the probe to pass-through (the engine's default: every survivor matches). */
export function clearJimmolateProbe(): void {
    currentProbe = () => true;
}

/** Turn the Jimmolate predicate layer on/off (was `Program.enableJimmolate()`). */
export function enableJimmolate(on = true): void {
    Jimmolate.enabled = on;
}

// ── Search ──
export type EngineSearchMode = "aesthetic" | "seedlist" | "random" | "sequential";

export interface RunSearchOptions {
    seeds?: string[];
    count?: number;
    aesthetic?: JamlAesthetic | number;
    startBatchIndex?: bigint;
    endBatchIndex?: bigint;
    batchCharacterCount?: number;
}

// v23's aesthetics no longer have a dedicated `runAestheticSearch`. They are seed
// keyword sets generated by MotelyUtilities; an aesthetic search is those seeds
// run through searchList. This reconstructs the removed entry point; the
// palindrome/echo lengths mirror Balatro's 8-char seed space.
export function aestheticSeeds(aesthetic: JamlAesthetic | number): string[] {
    switch (aesthetic as JamlAesthetic) {
        case JamlAesthetic.Gross:
            return MotelyUtilities.grossKeywords();
        case JamlAesthetic.Funny:
            return MotelyUtilities.funnyKeywords();
        case JamlAesthetic.Balatro:
            return MotelyUtilities.balatroKeywords();
        case JamlAesthetic.Palindrome:
            return MotelyUtilities.mirrorPatternKeywords(8);
        case JamlAesthetic.Echo:
            return MotelyUtilities.repeatCharKeywords(8);
        default:
            return MotelyUtilities.balatroKeywords();
    }
}

/**
 * Run a search to completion against an already-parsed config.
 *
 * v23 searches are fire-and-forget Promises (no IMotelySearch handle, no
 * mid-search cancel). Subscribe to MotelySearch.onProgress / onScoredResult /
 * onSeedMatch BEFORE calling this; the returned Promise resolves when the engine
 * finishes. Callers cancel by tearing down their runtime (e.g. terminating the
 * worker) — there is no engine-level cancel in v23.
 */
export function runSearch(config: JamlConfig, mode: EngineSearchMode, opts: RunSearchOptions = {}): Promise<void> {
    switch (mode) {
        case "seedlist":
            if (opts.seeds) config.seeds = opts.seeds;
            return MotelySearch.searchList(config);
        case "random":
            return MotelySearch.searchRandom(config, opts.count && opts.count > 0 ? opts.count : 0);
        case "sequential":
            return MotelySearch.searchSequential(
                config,
                opts.startBatchIndex ?? 0n,
                opts.endBatchIndex ?? 0n,
                opts.batchCharacterCount ?? 0,
            );
        case "aesthetic":
            config.seeds = aestheticSeeds(opts.aesthetic ?? JamlAesthetic.Balatro);
            return MotelySearch.searchList(config);
        default:
            return MotelySearch.searchList(config);
    }
}

// ── Analyzer ──
/** Analyze one or more seeds against a parsed config (was `Program.jamlyzer`). */
export function analyzeSeeds(config: JamlConfig): MotelyJamlyzerSeedResult[] {
    return MotelyJamlyzer.analyzeSeeds(config);
}

// Must match the path the host serves motely-wasm's bin/ at. Used by main-thread
// hooks, workers, and Storybook staticDir alike.
export const MOTELY_BIN_PATH = "/motely-wasm/bin";

// File System for the JAML library: motely-wasm@23 removed the engine-side ops
// (IFileMounter / pickRoot / mountRoot / readTextFile / writeTextFile) and the
// `@rewaffle/bootsharp-file-system` peer. But JAML files are plain text, so the
// library doesn't need the engine at all — useJamlLibrary now backs the mount
// directly on the browser File System Access API. These helpers report whether
// that API is actually available (Chromium-based browser over https), so the
// "unsupported" path is honest rather than faked.
export function isFileSystemReady(): boolean {
    return (
        typeof window !== "undefined" &&
        window.isSecureContext === true &&
        typeof (window as unknown as { showDirectoryPicker?: unknown }).showDirectoryPicker === "function"
    );
}

/** The reason the File System Access API is unavailable, or null when it's ready. */
export function getFileSystemError(): unknown {
    return isFileSystemReady()
        ? null
        : new Error("This browser has no File System Access API (needs a Chromium-based browser over https).");
}

// Single boot promise: boot() runs exactly once and is awaited by every caller.
let bootPromise: Promise<void> | null = null;

export async function ensureMotelyReady(): Promise<void> {
    if (bootPromise) return bootPromise;
    if (bootsharp.getStatus() !== bootsharp.BootStatus.Standby) return;
    bootPromise = (async () => {
        // motely-wasm is an EMBEDDED build (the runtime is inlined into the JS as
        // base64 — see dist/generated/resources.g.mjs), so boot() takes no args and
        // needs no served binaries.
        await bootsharp.boot();
    })();
    return bootPromise;
}
