<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net10.0-browser</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <!-- Desktop AOT -->
  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-browser'">
    <RunAOTCompilation>true</RunAOTCompilation>
    <WasmStripILAfterAOT>true</WasmStripILAfterAOT>
    <PublishAot>false</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Motely\Motely.csproj" />
  </ItemGroup>
</Project>
