export interface MotelyItemFormatEntry {
  readonly value: number;
  readonly enumName: string;
  readonly displayName: string;
  readonly category: string;
}

export declare const MOTELY_ITEM_FORMATS_BY_VALUE: {
  readonly 4096: { readonly value: 4096; readonly enumName: "TwoOfClubs"; readonly displayName: "2 of Clubs"; readonly category: "Standardcard"; };
  readonly 4097: { readonly value: 4097; readonly enumName: "ThreeOfClubs"; readonly displayName: "3 of Clubs"; readonly category: "Standardcard"; };
  readonly 4098: { readonly value: 4098; readonly enumName: "FourOfClubs"; readonly displayName: "4 of Clubs"; readonly category: "Standardcard"; };
  readonly 4099: { readonly value: 4099; readonly enumName: "FiveOfClubs"; readonly displayName: "5 of Clubs"; readonly category: "Standardcard"; };
  readonly 4100: { readonly value: 4100; readonly enumName: "SixOfClubs"; readonly displayName: "6 of Clubs"; readonly category: "Standardcard"; };
  readonly 4101: { readonly value: 4101; readonly enumName: "SevenOfClubs"; readonly displayName: "7 of Clubs"; readonly category: "Standardcard"; };
  readonly 4102: { readonly value: 4102; readonly enumName: "EightOfClubs"; readonly displayName: "8 of Clubs"; readonly category: "Standardcard"; };
  readonly 4103: { readonly value: 4103; readonly enumName: "NineOfClubs"; readonly displayName: "9 of Clubs"; readonly category: "Standardcard"; };
  readonly 4104: { readonly value: 4104; readonly enumName: "TenOfClubs"; readonly displayName: "10 of Clubs"; readonly category: "Standardcard"; };
  readonly 4105: { readonly value: 4105; readonly enumName: "JackOfClubs"; readonly displayName: "Jack of Clubs"; readonly category: "Standardcard"; };
  readonly 4106: { readonly value: 4106; readonly enumName: "QueenOfClubs"; readonly displayName: "Queen of Clubs"; readonly category: "Standardcard"; };
  readonly 4107: { readonly value: 4107; readonly enumName: "KingOfClubs"; readonly displayName: "King of Clubs"; readonly category: "Standardcard"; };
  readonly 4108: { readonly value: 4108; readonly enumName: "AceOfClubs"; readonly displayName: "Ace of Clubs"; readonly category: "Standardcard"; };
  readonly 4112: { readonly value: 4112; readonly enumName: "TwoOfDiamonds"; readonly displayName: "2 of Diamonds"; readonly category: "Standardcard"; };
  readonly 4113: { readonly value: 4113; readonly enumName: "ThreeOfDiamonds"; readonly displayName: "3 of Diamonds"; readonly category: "Standardcard"; };
  readonly 4114: { readonly value: 4114; readonly enumName: "FourOfDiamonds"; readonly displayName: "4 of Diamonds"; readonly category: "Standardcard"; };
  readonly 4115: { readonly value: 4115; readonly enumName: "FiveOfDiamonds"; readonly displayName: "5 of Diamonds"; readonly category: "Standardcard"; };
  readonly 4116: { readonly value: 4116; readonly enumName: "SixOfDiamonds"; readonly displayName: "6 of Diamonds"; readonly category: "Standardcard"; };
  readonly 4117: { readonly value: 4117; readonly enumName: "SevenOfDiamonds"; readonly displayName: "7 of Diamonds"; readonly category: "Standardcard"; };
  readonly 4118: { readonly value: 4118; readonly enumName: "EightOfDiamonds"; readonly displayName: "8 of Diamonds"; readonly category: "Standardcard"; };
  readonly 4119: { readonly value: 4119; readonly enumName: "NineOfDiamonds"; readonly displayName: "9 of Diamonds"; readonly category: "Standardcard"; };
  readonly 4120: { readonly value: 4120; readonly enumName: "TenOfDiamonds"; readonly displayName: "10 of Diamonds"; readonly category: "Standardcard"; };
  readonly 4121: { readonly value: 4121; readonly enumName: "JackOfDiamonds"; readonly displayName: "Jack of Diamonds"; readonly category: "Standardcard"; };
  readonly 4122: { readonly value: 4122; readonly enumName: "QueenOfDiamonds"; readonly displayName: "Queen of Diamonds"; readonly category: "Standardcard"; };
  readonly 4123: { readonly value: 4123; readonly enumName: "KingOfDiamonds"; readonly displayName: "King of Diamonds"; readonly category: "Standardcard"; };
  readonly 4124: { readonly value: 4124; readonly enumName: "AceOfDiamonds"; readonly displayName: "Ace of Diamonds"; readonly category: "Standardcard"; };
  readonly 4128: { readonly value: 4128; readonly enumName: "TwoOfHearts"; readonly displayName: "2 of Hearts"; readonly category: "Standardcard"; };
  readonly 4129: { readonly value: 4129; readonly enumName: "ThreeOfHearts"; readonly displayName: "3 of Hearts"; readonly category: "Standardcard"; };
  readonly 4130: { readonly value: 4130; readonly enumName: "FourOfHearts"; readonly displayName: "4 of Hearts"; readonly category: "Standardcard"; };
  readonly 4131: { readonly value: 4131; readonly enumName: "FiveOfHearts"; readonly displayName: "5 of Hearts"; readonly category: "Standardcard"; };
  readonly 4132: { readonly value: 4132; readonly enumName: "SixOfHearts"; readonly displayName: "6 of Hearts"; readonly category: "Standardcard"; };
  readonly 4133: { readonly value: 4133; readonly enumName: "SevenOfHearts"; readonly displayName: "7 of Hearts"; readonly category: "Standardcard"; };
  readonly 4134: { readonly value: 4134; readonly enumName: "EightOfHearts"; readonly displayName: "8 of Hearts"; readonly category: "Standardcard"; };
  readonly 4135: { readonly value: 4135; readonly enumName: "NineOfHearts"; readonly displayName: "9 of Hearts"; readonly category: "Standardcard"; };
  readonly 4136: { readonly value: 4136; readonly enumName: "TenOfHearts"; readonly displayName: "10 of Hearts"; readonly category: "Standardcard"; };
  readonly 4137: { readonly value: 4137; readonly enumName: "JackOfHearts"; readonly displayName: "Jack of Hearts"; readonly category: "Standardcard"; };
  readonly 4138: { readonly value: 4138; readonly enumName: "QueenOfHearts"; readonly displayName: "Queen of Hearts"; readonly category: "Standardcard"; };
  readonly 4139: { readonly value: 4139; readonly enumName: "KingOfHearts"; readonly displayName: "King of Hearts"; readonly category: "Standardcard"; };
  readonly 4140: { readonly value: 4140; readonly enumName: "AceOfHearts"; readonly displayName: "Ace of Hearts"; readonly category: "Standardcard"; };
  readonly 4144: { readonly value: 4144; readonly enumName: "TwoOfSpades"; readonly displayName: "2 of Spades"; readonly category: "Standardcard"; };
  readonly 4145: { readonly value: 4145; readonly enumName: "ThreeOfSpades"; readonly displayName: "3 of Spades"; readonly category: "Standardcard"; };
  readonly 4146: { readonly value: 4146; readonly enumName: "FourOfSpades"; readonly displayName: "4 of Spades"; readonly category: "Standardcard"; };
  readonly 4147: { readonly value: 4147; readonly enumName: "FiveOfSpades"; readonly displayName: "5 of Spades"; readonly category: "Standardcard"; };
  readonly 4148: { readonly value: 4148; readonly enumName: "SixOfSpades"; readonly displayName: "6 of Spades"; readonly category: "Standardcard"; };
  readonly 4149: { readonly value: 4149; readonly enumName: "SevenOfSpades"; readonly displayName: "7 of Spades"; readonly category: "Standardcard"; };
  readonly 4150: { readonly value: 4150; readonly enumName: "EightOfSpades"; readonly displayName: "8 of Spades"; readonly category: "Standardcard"; };
  readonly 4151: { readonly value: 4151; readonly enumName: "NineOfSpades"; readonly displayName: "9 of Spades"; readonly category: "Standardcard"; };
  readonly 4152: { readonly value: 4152; readonly enumName: "TenOfSpades"; readonly displayName: "10 of Spades"; readonly category: "Standardcard"; };
  readonly 4153: { readonly value: 4153; readonly enumName: "JackOfSpades"; readonly displayName: "Jack of Spades"; readonly category: "Standardcard"; };
  readonly 4154: { readonly value: 4154; readonly enumName: "QueenOfSpades"; readonly displayName: "Queen of Spades"; readonly category: "Standardcard"; };
  readonly 4155: { readonly value: 4155; readonly enumName: "KingOfSpades"; readonly displayName: "King of Spades"; readonly category: "Standardcard"; };
  readonly 4156: { readonly value: 4156; readonly enumName: "AceOfSpades"; readonly displayName: "Ace of Spades"; readonly category: "Standardcard"; };
  readonly 8192: { readonly value: 8192; readonly enumName: "Familiar"; readonly displayName: "Familiar"; readonly category: "SpectralCard"; };
  readonly 8193: { readonly value: 8193; readonly enumName: "Grim"; readonly displayName: "Grim"; readonly category: "SpectralCard"; };
  readonly 8194: { readonly value: 8194; readonly enumName: "Incantation"; readonly displayName: "Incantation"; readonly category: "SpectralCard"; };
  readonly 8195: { readonly value: 8195; readonly enumName: "Talisman"; readonly displayName: "Talisman"; readonly category: "SpectralCard"; };
  readonly 8196: { readonly value: 8196; readonly enumName: "Aura"; readonly displayName: "Aura"; readonly category: "SpectralCard"; };
  readonly 8197: { readonly value: 8197; readonly enumName: "Wraith"; readonly displayName: "Wraith"; readonly category: "SpectralCard"; };
  readonly 8198: { readonly value: 8198; readonly enumName: "Sigil"; readonly displayName: "Sigil"; readonly category: "SpectralCard"; };
  readonly 8199: { readonly value: 8199; readonly enumName: "Ouija"; readonly displayName: "Ouija"; readonly category: "SpectralCard"; };
  readonly 8200: { readonly value: 8200; readonly enumName: "Ectoplasm"; readonly displayName: "Ectoplasm"; readonly category: "SpectralCard"; };
  readonly 8201: { readonly value: 8201; readonly enumName: "Immolate"; readonly displayName: "Immolate"; readonly category: "SpectralCard"; };
  readonly 8202: { readonly value: 8202; readonly enumName: "Ankh"; readonly displayName: "Ankh"; readonly category: "SpectralCard"; };
  readonly 8203: { readonly value: 8203; readonly enumName: "DejaVu"; readonly displayName: "Deja Vu"; readonly category: "SpectralCard"; };
  readonly 8204: { readonly value: 8204; readonly enumName: "Hex"; readonly displayName: "Hex"; readonly category: "SpectralCard"; };
  readonly 8205: { readonly value: 8205; readonly enumName: "Trance"; readonly displayName: "Trance"; readonly category: "SpectralCard"; };
  readonly 8206: { readonly value: 8206; readonly enumName: "Medium"; readonly displayName: "Medium"; readonly category: "SpectralCard"; };
  readonly 8207: { readonly value: 8207; readonly enumName: "Cryptid"; readonly displayName: "Cryptid"; readonly category: "SpectralCard"; };
  readonly 8208: { readonly value: 8208; readonly enumName: "TheSoul"; readonly displayName: "The Soul"; readonly category: "SpectralCard"; };
  readonly 8209: { readonly value: 8209; readonly enumName: "BlackHole"; readonly displayName: "Black Hole"; readonly category: "SpectralCard"; };
  readonly 12288: { readonly value: 12288; readonly enumName: "TheFool"; readonly displayName: "The Fool"; readonly category: "TarotCard"; };
  readonly 12289: { readonly value: 12289; readonly enumName: "TheMagician"; readonly displayName: "The Magician"; readonly category: "TarotCard"; };
  readonly 12290: { readonly value: 12290; readonly enumName: "TheHighPriestess"; readonly displayName: "The High Priestess"; readonly category: "TarotCard"; };
  readonly 12291: { readonly value: 12291; readonly enumName: "TheEmpress"; readonly displayName: "The Empress"; readonly category: "TarotCard"; };
  readonly 12292: { readonly value: 12292; readonly enumName: "TheEmperor"; readonly displayName: "The Emperor"; readonly category: "TarotCard"; };
  readonly 12293: { readonly value: 12293; readonly enumName: "TheHierophant"; readonly displayName: "The Hierophant"; readonly category: "TarotCard"; };
  readonly 12294: { readonly value: 12294; readonly enumName: "TheLovers"; readonly displayName: "The Lovers"; readonly category: "TarotCard"; };
  readonly 12295: { readonly value: 12295; readonly enumName: "TheChariot"; readonly displayName: "The Chariot"; readonly category: "TarotCard"; };
  readonly 12296: { readonly value: 12296; readonly enumName: "Justice"; readonly displayName: "Justice"; readonly category: "TarotCard"; };
  readonly 12297: { readonly value: 12297; readonly enumName: "TheHermit"; readonly displayName: "The Hermit"; readonly category: "TarotCard"; };
  readonly 12298: { readonly value: 12298; readonly enumName: "TheWheelOfFortune"; readonly displayName: "The Wheel of Fortune"; readonly category: "TarotCard"; };
  readonly 12299: { readonly value: 12299; readonly enumName: "Strength"; readonly displayName: "Strength"; readonly category: "TarotCard"; };
  readonly 12300: { readonly value: 12300; readonly enumName: "TheHangedMan"; readonly displayName: "The Hanged Man"; readonly category: "TarotCard"; };
  readonly 12301: { readonly value: 12301; readonly enumName: "Death"; readonly displayName: "Death"; readonly category: "TarotCard"; };
  readonly 12302: { readonly value: 12302; readonly enumName: "Temperance"; readonly displayName: "Temperance"; readonly category: "TarotCard"; };
  readonly 12303: { readonly value: 12303; readonly enumName: "TheDevil"; readonly displayName: "The Devil"; readonly category: "TarotCard"; };
  readonly 12304: { readonly value: 12304; readonly enumName: "TheTower"; readonly displayName: "The Tower"; readonly category: "TarotCard"; };
  readonly 12305: { readonly value: 12305; readonly enumName: "TheStar"; readonly displayName: "The Star"; readonly category: "TarotCard"; };
  readonly 12306: { readonly value: 12306; readonly enumName: "TheMoon"; readonly displayName: "The Moon"; readonly category: "TarotCard"; };
  readonly 12307: { readonly value: 12307; readonly enumName: "TheSun"; readonly displayName: "The Sun"; readonly category: "TarotCard"; };
  readonly 12308: { readonly value: 12308; readonly enumName: "Judgement"; readonly displayName: "Judgement"; readonly category: "TarotCard"; };
  readonly 12309: { readonly value: 12309; readonly enumName: "TheWorld"; readonly displayName: "The World"; readonly category: "TarotCard"; };
  readonly 16384: { readonly value: 16384; readonly enumName: "Mercury"; readonly displayName: "Mercury"; readonly category: "PlanetCard"; };
  readonly 16385: { readonly value: 16385; readonly enumName: "Venus"; readonly displayName: "Venus"; readonly category: "PlanetCard"; };
  readonly 16386: { readonly value: 16386; readonly enumName: "Earth"; readonly displayName: "Earth"; readonly category: "PlanetCard"; };
  readonly 16387: { readonly value: 16387; readonly enumName: "Mars"; readonly displayName: "Mars"; readonly category: "PlanetCard"; };
  readonly 16388: { readonly value: 16388; readonly enumName: "Jupiter"; readonly displayName: "Jupiter"; readonly category: "PlanetCard"; };
  readonly 16389: { readonly value: 16389; readonly enumName: "Saturn"; readonly displayName: "Saturn"; readonly category: "PlanetCard"; };
  readonly 16390: { readonly value: 16390; readonly enumName: "Uranus"; readonly displayName: "Uranus"; readonly category: "PlanetCard"; };
  readonly 16391: { readonly value: 16391; readonly enumName: "Neptune"; readonly displayName: "Neptune"; readonly category: "PlanetCard"; };
  readonly 16392: { readonly value: 16392; readonly enumName: "Pluto"; readonly displayName: "Pluto"; readonly category: "PlanetCard"; };
  readonly 16393: { readonly value: 16393; readonly enumName: "PlanetX"; readonly displayName: "Planet X"; readonly category: "PlanetCard"; };
  readonly 16394: { readonly value: 16394; readonly enumName: "Ceres"; readonly displayName: "Ceres"; readonly category: "PlanetCard"; };
  readonly 16395: { readonly value: 16395; readonly enumName: "Eris"; readonly displayName: "Eris"; readonly category: "PlanetCard"; };
  readonly 20480: { readonly value: 20480; readonly enumName: "Joker"; readonly displayName: "Joker"; readonly category: "Joker"; };
  readonly 20481: { readonly value: 20481; readonly enumName: "GreedyJoker"; readonly displayName: "Greedy Joker"; readonly category: "Joker"; };
  readonly 20482: { readonly value: 20482; readonly enumName: "LustyJoker"; readonly displayName: "Lusty Joker"; readonly category: "Joker"; };
  readonly 20483: { readonly value: 20483; readonly enumName: "WrathfulJoker"; readonly displayName: "Wrathful Joker"; readonly category: "Joker"; };
  readonly 20484: { readonly value: 20484; readonly enumName: "GluttonousJoker"; readonly displayName: "Gluttonous Joker"; readonly category: "Joker"; };
  readonly 20485: { readonly value: 20485; readonly enumName: "JollyJoker"; readonly displayName: "Jolly Joker"; readonly category: "Joker"; };
  readonly 20486: { readonly value: 20486; readonly enumName: "ZanyJoker"; readonly displayName: "Zany Joker"; readonly category: "Joker"; };
  readonly 20487: { readonly value: 20487; readonly enumName: "MadJoker"; readonly displayName: "Mad Joker"; readonly category: "Joker"; };
  readonly 20488: { readonly value: 20488; readonly enumName: "CrazyJoker"; readonly displayName: "Crazy Joker"; readonly category: "Joker"; };
  readonly 20489: { readonly value: 20489; readonly enumName: "DrollJoker"; readonly displayName: "Droll Joker"; readonly category: "Joker"; };
  readonly 20490: { readonly value: 20490; readonly enumName: "SlyJoker"; readonly displayName: "Sly Joker"; readonly category: "Joker"; };
  readonly 20491: { readonly value: 20491; readonly enumName: "WilyJoker"; readonly displayName: "Wily Joker"; readonly category: "Joker"; };
  readonly 20492: { readonly value: 20492; readonly enumName: "CleverJoker"; readonly displayName: "Clever Joker"; readonly category: "Joker"; };
  readonly 20493: { readonly value: 20493; readonly enumName: "DeviousJoker"; readonly displayName: "Devious Joker"; readonly category: "Joker"; };
  readonly 20494: { readonly value: 20494; readonly enumName: "CraftyJoker"; readonly displayName: "Crafty Joker"; readonly category: "Joker"; };
  readonly 20495: { readonly value: 20495; readonly enumName: "HalfJoker"; readonly displayName: "Half Joker"; readonly category: "Joker"; };
  readonly 20496: { readonly value: 20496; readonly enumName: "CreditCard"; readonly displayName: "Credit Card"; readonly category: "Joker"; };
  readonly 20497: { readonly value: 20497; readonly enumName: "Banner"; readonly displayName: "Banner"; readonly category: "Joker"; };
  readonly 20498: { readonly value: 20498; readonly enumName: "MysticSummit"; readonly displayName: "Mystic Summit"; readonly category: "Joker"; };
  readonly 20499: { readonly value: 20499; readonly enumName: "EightBall"; readonly displayName: "8 Ball"; readonly category: "Joker"; };
  readonly 20500: { readonly value: 20500; readonly enumName: "Misprint"; readonly displayName: "Misprint"; readonly category: "Joker"; };
  readonly 20501: { readonly value: 20501; readonly enumName: "RaisedFist"; readonly displayName: "Raised Fist"; readonly category: "Joker"; };
  readonly 20502: { readonly value: 20502; readonly enumName: "ChaostheClown"; readonly displayName: "Chaos the Clown"; readonly category: "Joker"; };
  readonly 20503: { readonly value: 20503; readonly enumName: "ScaryFace"; readonly displayName: "Scary Face"; readonly category: "Joker"; };
  readonly 20504: { readonly value: 20504; readonly enumName: "AbstractJoker"; readonly displayName: "Abstract Joker"; readonly category: "Joker"; };
  readonly 20505: { readonly value: 20505; readonly enumName: "DelayedGratification"; readonly displayName: "Delayed Gratification"; readonly category: "Joker"; };
  readonly 20506: { readonly value: 20506; readonly enumName: "GrosMichel"; readonly displayName: "Gros Michel"; readonly category: "Joker"; };
  readonly 20507: { readonly value: 20507; readonly enumName: "EvenSteven"; readonly displayName: "Even Steven"; readonly category: "Joker"; };
  readonly 20508: { readonly value: 20508; readonly enumName: "OddTodd"; readonly displayName: "Odd Todd"; readonly category: "Joker"; };
  readonly 20509: { readonly value: 20509; readonly enumName: "Scholar"; readonly displayName: "Scholar"; readonly category: "Joker"; };
  readonly 20510: { readonly value: 20510; readonly enumName: "BusinessCard"; readonly displayName: "Business Card"; readonly category: "Joker"; };
  readonly 20511: { readonly value: 20511; readonly enumName: "Supernova"; readonly displayName: "Supernova"; readonly category: "Joker"; };
  readonly 20512: { readonly value: 20512; readonly enumName: "RideTheBus"; readonly displayName: "Ride the Bus"; readonly category: "Joker"; };
  readonly 20513: { readonly value: 20513; readonly enumName: "Egg"; readonly displayName: "Egg"; readonly category: "Joker"; };
  readonly 20514: { readonly value: 20514; readonly enumName: "Runner"; readonly displayName: "Runner"; readonly category: "Joker"; };
  readonly 20515: { readonly value: 20515; readonly enumName: "IceCream"; readonly displayName: "Ice Cream"; readonly category: "Joker"; };
  readonly 20516: { readonly value: 20516; readonly enumName: "Splash"; readonly displayName: "Splash"; readonly category: "Joker"; };
  readonly 20517: { readonly value: 20517; readonly enumName: "BlueJoker"; readonly displayName: "Blue Joker"; readonly category: "Joker"; };
  readonly 20518: { readonly value: 20518; readonly enumName: "FacelessJoker"; readonly displayName: "Faceless Joker"; readonly category: "Joker"; };
  readonly 20519: { readonly value: 20519; readonly enumName: "GreenJoker"; readonly displayName: "Green Joker"; readonly category: "Joker"; };
  readonly 20520: { readonly value: 20520; readonly enumName: "Superposition"; readonly displayName: "Superposition"; readonly category: "Joker"; };
  readonly 20521: { readonly value: 20521; readonly enumName: "ToDoList"; readonly displayName: "To Do List"; readonly category: "Joker"; };
  readonly 20522: { readonly value: 20522; readonly enumName: "Cavendish"; readonly displayName: "Cavendish"; readonly category: "Joker"; };
  readonly 20523: { readonly value: 20523; readonly enumName: "RedCard"; readonly displayName: "Red Card"; readonly category: "Joker"; };
  readonly 20524: { readonly value: 20524; readonly enumName: "SquareJoker"; readonly displayName: "Square Joker"; readonly category: "Joker"; };
  readonly 20525: { readonly value: 20525; readonly enumName: "RiffRaff"; readonly displayName: "Riff-raff"; readonly category: "Joker"; };
  readonly 20526: { readonly value: 20526; readonly enumName: "Photograph"; readonly displayName: "Photograph"; readonly category: "Joker"; };
  readonly 20527: { readonly value: 20527; readonly enumName: "ReservedParking"; readonly displayName: "Reserved Parking"; readonly category: "Joker"; };
  readonly 20528: { readonly value: 20528; readonly enumName: "MailInRebate"; readonly displayName: "Mail In Rebate"; readonly category: "Joker"; };
  readonly 20529: { readonly value: 20529; readonly enumName: "Hallucination"; readonly displayName: "Hallucination"; readonly category: "Joker"; };
  readonly 20530: { readonly value: 20530; readonly enumName: "FortuneTeller"; readonly displayName: "Fortune Teller"; readonly category: "Joker"; };
  readonly 20531: { readonly value: 20531; readonly enumName: "Juggler"; readonly displayName: "Juggler"; readonly category: "Joker"; };
  readonly 20532: { readonly value: 20532; readonly enumName: "Drunkard"; readonly displayName: "Drunkard"; readonly category: "Joker"; };
  readonly 20533: { readonly value: 20533; readonly enumName: "GoldenJoker"; readonly displayName: "Golden Joker"; readonly category: "Joker"; };
  readonly 20534: { readonly value: 20534; readonly enumName: "Popcorn"; readonly displayName: "Popcorn"; readonly category: "Joker"; };
  readonly 20535: { readonly value: 20535; readonly enumName: "WalkieTalkie"; readonly displayName: "Walkie Talkie"; readonly category: "Joker"; };
  readonly 20536: { readonly value: 20536; readonly enumName: "SmileyFace"; readonly displayName: "Smiley Face"; readonly category: "Joker"; };
  readonly 20537: { readonly value: 20537; readonly enumName: "GoldenTicket"; readonly displayName: "Golden Ticket"; readonly category: "Joker"; };
  readonly 20538: { readonly value: 20538; readonly enumName: "Swashbuckler"; readonly displayName: "Swashbuckler"; readonly category: "Joker"; };
  readonly 20539: { readonly value: 20539; readonly enumName: "HangingChad"; readonly displayName: "Hanging Chad"; readonly category: "Joker"; };
  readonly 20540: { readonly value: 20540; readonly enumName: "ShootTheMoon"; readonly displayName: "Shoot the Moon"; readonly category: "Joker"; };
  readonly 21504: { readonly value: 21504; readonly enumName: "JokerStencil"; readonly displayName: "Joker Stencil"; readonly category: "Joker"; };
  readonly 21505: { readonly value: 21505; readonly enumName: "FourFingers"; readonly displayName: "Four Fingers"; readonly category: "Joker"; };
  readonly 21506: { readonly value: 21506; readonly enumName: "Mime"; readonly displayName: "Mime"; readonly category: "Joker"; };
  readonly 21507: { readonly value: 21507; readonly enumName: "CeremonialDagger"; readonly displayName: "Ceremonial Dagger"; readonly category: "Joker"; };
  readonly 21508: { readonly value: 21508; readonly enumName: "MarbleJoker"; readonly displayName: "Marble Joker"; readonly category: "Joker"; };
  readonly 21509: { readonly value: 21509; readonly enumName: "LoyaltyCard"; readonly displayName: "Loyalty Card"; readonly category: "Joker"; };
  readonly 21510: { readonly value: 21510; readonly enumName: "Dusk"; readonly displayName: "Dusk"; readonly category: "Joker"; };
  readonly 21511: { readonly value: 21511; readonly enumName: "Fibonacci"; readonly displayName: "Fibonacci"; readonly category: "Joker"; };
  readonly 21512: { readonly value: 21512; readonly enumName: "SteelJoker"; readonly displayName: "Steel Joker"; readonly category: "Joker"; };
  readonly 21513: { readonly value: 21513; readonly enumName: "Hack"; readonly displayName: "Hack"; readonly category: "Joker"; };
  readonly 21514: { readonly value: 21514; readonly enumName: "Pareidolia"; readonly displayName: "Pareidolia"; readonly category: "Joker"; };
  readonly 21515: { readonly value: 21515; readonly enumName: "SpaceJoker"; readonly displayName: "Space Joker"; readonly category: "Joker"; };
  readonly 21516: { readonly value: 21516; readonly enumName: "Burglar"; readonly displayName: "Burglar"; readonly category: "Joker"; };
  readonly 21517: { readonly value: 21517; readonly enumName: "Blackboard"; readonly displayName: "Blackboard"; readonly category: "Joker"; };
  readonly 21518: { readonly value: 21518; readonly enumName: "SixthSense"; readonly displayName: "Sixth Sense"; readonly category: "Joker"; };
  readonly 21519: { readonly value: 21519; readonly enumName: "Constellation"; readonly displayName: "Constellation"; readonly category: "Joker"; };
  readonly 21520: { readonly value: 21520; readonly enumName: "Hiker"; readonly displayName: "Hiker"; readonly category: "Joker"; };
  readonly 21521: { readonly value: 21521; readonly enumName: "CardSharp"; readonly displayName: "Card Sharp"; readonly category: "Joker"; };
  readonly 21522: { readonly value: 21522; readonly enumName: "Madness"; readonly displayName: "Madness"; readonly category: "Joker"; };
  readonly 21523: { readonly value: 21523; readonly enumName: "Seance"; readonly displayName: "Seance"; readonly category: "Joker"; };
  readonly 21524: { readonly value: 21524; readonly enumName: "Vampire"; readonly displayName: "Vampire"; readonly category: "Joker"; };
  readonly 21525: { readonly value: 21525; readonly enumName: "Shortcut"; readonly displayName: "Shortcut"; readonly category: "Joker"; };
  readonly 21526: { readonly value: 21526; readonly enumName: "Hologram"; readonly displayName: "Hologram"; readonly category: "Joker"; };
  readonly 21527: { readonly value: 21527; readonly enumName: "Cloud9"; readonly displayName: "Cloud 9"; readonly category: "Joker"; };
  readonly 21528: { readonly value: 21528; readonly enumName: "Rocket"; readonly displayName: "Rocket"; readonly category: "Joker"; };
  readonly 21529: { readonly value: 21529; readonly enumName: "MidasMask"; readonly displayName: "Midas Mask"; readonly category: "Joker"; };
  readonly 21530: { readonly value: 21530; readonly enumName: "Luchador"; readonly displayName: "Luchador"; readonly category: "Joker"; };
  readonly 21531: { readonly value: 21531; readonly enumName: "GiftCard"; readonly displayName: "Gift Card"; readonly category: "Joker"; };
  readonly 21532: { readonly value: 21532; readonly enumName: "TurtleBean"; readonly displayName: "Turtle Bean"; readonly category: "Joker"; };
  readonly 21533: { readonly value: 21533; readonly enumName: "Erosion"; readonly displayName: "Erosion"; readonly category: "Joker"; };
  readonly 21534: { readonly value: 21534; readonly enumName: "ToTheMoon"; readonly displayName: "To the Moon"; readonly category: "Joker"; };
  readonly 21535: { readonly value: 21535; readonly enumName: "StoneJoker"; readonly displayName: "Stone Joker"; readonly category: "Joker"; };
  readonly 21536: { readonly value: 21536; readonly enumName: "LuckyCat"; readonly displayName: "Lucky Cat"; readonly category: "Joker"; };
  readonly 21537: { readonly value: 21537; readonly enumName: "Bull"; readonly displayName: "Bull"; readonly category: "Joker"; };
  readonly 21538: { readonly value: 21538; readonly enumName: "DietCola"; readonly displayName: "Diet Cola"; readonly category: "Joker"; };
  readonly 21539: { readonly value: 21539; readonly enumName: "TradingCard"; readonly displayName: "Trading Card"; readonly category: "Joker"; };
  readonly 21540: { readonly value: 21540; readonly enumName: "FlashCard"; readonly displayName: "Flash Card"; readonly category: "Joker"; };
  readonly 21541: { readonly value: 21541; readonly enumName: "SpareTrousers"; readonly displayName: "Spare Trousers"; readonly category: "Joker"; };
  readonly 21542: { readonly value: 21542; readonly enumName: "Ramen"; readonly displayName: "Ramen"; readonly category: "Joker"; };
  readonly 21543: { readonly value: 21543; readonly enumName: "Seltzer"; readonly displayName: "Seltzer"; readonly category: "Joker"; };
  readonly 21544: { readonly value: 21544; readonly enumName: "Castle"; readonly displayName: "Castle"; readonly category: "Joker"; };
  readonly 21545: { readonly value: 21545; readonly enumName: "MrBones"; readonly displayName: "Mr. Bones"; readonly category: "Joker"; };
  readonly 21546: { readonly value: 21546; readonly enumName: "Acrobat"; readonly displayName: "Acrobat"; readonly category: "Joker"; };
  readonly 21547: { readonly value: 21547; readonly enumName: "SockAndBuskin"; readonly displayName: "Sock and Buskin"; readonly category: "Joker"; };
  readonly 21548: { readonly value: 21548; readonly enumName: "Troubadour"; readonly displayName: "Troubadour"; readonly category: "Joker"; };
  readonly 21549: { readonly value: 21549; readonly enumName: "Certificate"; readonly displayName: "Certificate"; readonly category: "Joker"; };
  readonly 21550: { readonly value: 21550; readonly enumName: "SmearedJoker"; readonly displayName: "Smeared Joker"; readonly category: "Joker"; };
  readonly 21551: { readonly value: 21551; readonly enumName: "Throwback"; readonly displayName: "Throwback"; readonly category: "Joker"; };
  readonly 21552: { readonly value: 21552; readonly enumName: "RoughGem"; readonly displayName: "Rough Gem"; readonly category: "Joker"; };
  readonly 21553: { readonly value: 21553; readonly enumName: "Bloodstone"; readonly displayName: "Bloodstone"; readonly category: "Joker"; };
  readonly 21554: { readonly value: 21554; readonly enumName: "Arrowhead"; readonly displayName: "Arrowhead"; readonly category: "Joker"; };
  readonly 21555: { readonly value: 21555; readonly enumName: "OnyxAgate"; readonly displayName: "Onyx Agate"; readonly category: "Joker"; };
  readonly 21556: { readonly value: 21556; readonly enumName: "GlassJoker"; readonly displayName: "Glass Joker"; readonly category: "Joker"; };
  readonly 21557: { readonly value: 21557; readonly enumName: "Showman"; readonly displayName: "Showman"; readonly category: "Joker"; };
  readonly 21558: { readonly value: 21558; readonly enumName: "FlowerPot"; readonly displayName: "Flower Pot"; readonly category: "Joker"; };
  readonly 21559: { readonly value: 21559; readonly enumName: "MerryAndy"; readonly displayName: "Merry Andy"; readonly category: "Joker"; };
  readonly 21560: { readonly value: 21560; readonly enumName: "OopsAll6s"; readonly displayName: "Oops! All 6s"; readonly category: "Joker"; };
  readonly 21561: { readonly value: 21561; readonly enumName: "TheIdol"; readonly displayName: "The Idol"; readonly category: "Joker"; };
  readonly 21562: { readonly value: 21562; readonly enumName: "SeeingDouble"; readonly displayName: "Seeing Double"; readonly category: "Joker"; };
  readonly 21563: { readonly value: 21563; readonly enumName: "Matador"; readonly displayName: "Matador"; readonly category: "Joker"; };
  readonly 21564: { readonly value: 21564; readonly enumName: "Satellite"; readonly displayName: "Satellite"; readonly category: "Joker"; };
  readonly 21565: { readonly value: 21565; readonly enumName: "Cartomancer"; readonly displayName: "Cartomancer"; readonly category: "Joker"; };
  readonly 21566: { readonly value: 21566; readonly enumName: "Astronomer"; readonly displayName: "Astronomer"; readonly category: "Joker"; };
  readonly 21567: { readonly value: 21567; readonly enumName: "Bootstraps"; readonly displayName: "Bootstraps"; readonly category: "Joker"; };
  readonly 22528: { readonly value: 22528; readonly enumName: "DNA"; readonly displayName: "DNA"; readonly category: "Joker"; };
  readonly 22529: { readonly value: 22529; readonly enumName: "Vagabond"; readonly displayName: "Vagabond"; readonly category: "Joker"; };
  readonly 22530: { readonly value: 22530; readonly enumName: "Baron"; readonly displayName: "Baron"; readonly category: "Joker"; };
  readonly 22531: { readonly value: 22531; readonly enumName: "Obelisk"; readonly displayName: "Obelisk"; readonly category: "Joker"; };
  readonly 22532: { readonly value: 22532; readonly enumName: "BaseballCard"; readonly displayName: "Baseball Card"; readonly category: "Joker"; };
  readonly 22533: { readonly value: 22533; readonly enumName: "AncientJoker"; readonly displayName: "Ancient Joker"; readonly category: "Joker"; };
  readonly 22534: { readonly value: 22534; readonly enumName: "Campfire"; readonly displayName: "Campfire"; readonly category: "Joker"; };
  readonly 22535: { readonly value: 22535; readonly enumName: "Blueprint"; readonly displayName: "Blueprint"; readonly category: "Joker"; };
  readonly 22536: { readonly value: 22536; readonly enumName: "WeeJoker"; readonly displayName: "Wee Joker"; readonly category: "Joker"; };
  readonly 22537: { readonly value: 22537; readonly enumName: "HitTheRoad"; readonly displayName: "Hit the Road"; readonly category: "Joker"; };
  readonly 22538: { readonly value: 22538; readonly enumName: "TheDuo"; readonly displayName: "The Duo"; readonly category: "Joker"; };
  readonly 22539: { readonly value: 22539; readonly enumName: "TheTrio"; readonly displayName: "The Trio"; readonly category: "Joker"; };
  readonly 22540: { readonly value: 22540; readonly enumName: "TheFamily"; readonly displayName: "The Family"; readonly category: "Joker"; };
  readonly 22541: { readonly value: 22541; readonly enumName: "TheOrder"; readonly displayName: "The Order"; readonly category: "Joker"; };
  readonly 22542: { readonly value: 22542; readonly enumName: "TheTribe"; readonly displayName: "The Tribe"; readonly category: "Joker"; };
  readonly 22543: { readonly value: 22543; readonly enumName: "Stuntman"; readonly displayName: "Stuntman"; readonly category: "Joker"; };
  readonly 22544: { readonly value: 22544; readonly enumName: "InvisibleJoker"; readonly displayName: "Invisible Joker"; readonly category: "Joker"; };
  readonly 22545: { readonly value: 22545; readonly enumName: "Brainstorm"; readonly displayName: "Brainstorm"; readonly category: "Joker"; };
  readonly 22546: { readonly value: 22546; readonly enumName: "DriversLicense"; readonly displayName: "Driver\u0027s License"; readonly category: "Joker"; };
  readonly 22547: { readonly value: 22547; readonly enumName: "BurntJoker"; readonly displayName: "Burnt Joker"; readonly category: "Joker"; };
  readonly 23552: { readonly value: 23552; readonly enumName: "Canio"; readonly displayName: "Canio"; readonly category: "Joker"; };
  readonly 23553: { readonly value: 23553; readonly enumName: "Triboulet"; readonly displayName: "Triboulet"; readonly category: "Joker"; };
  readonly 23554: { readonly value: 23554; readonly enumName: "Yorick"; readonly displayName: "Yorick"; readonly category: "Joker"; };
  readonly 23555: { readonly value: 23555; readonly enumName: "Chicot"; readonly displayName: "Chicot"; readonly category: "Joker"; };
  readonly 23556: { readonly value: 23556; readonly enumName: "Perkeo"; readonly displayName: "Perkeo"; readonly category: "Joker"; };
  readonly 61440: { readonly value: 61440; readonly enumName: "Invalid"; readonly displayName: "Invalid"; readonly category: "Invalid"; };
  readonly 61441: { readonly value: 61441; readonly enumName: "NotImplemented"; readonly displayName: "Not Implemented"; readonly category: "Invalid"; };
  readonly 61442: { readonly value: 61442; readonly enumName: "JokerExcludedByStream"; readonly displayName: "Joker Excluded By Stream"; readonly category: "Invalid"; };
  readonly 61443: { readonly value: 61443; readonly enumName: "PlanetExcludedByStream"; readonly displayName: "Planet Excluded By Stream"; readonly category: "Invalid"; };
  readonly 61444: { readonly value: 61444; readonly enumName: "TarotExcludedByStream"; readonly displayName: "Tarot Excluded By Stream"; readonly category: "Invalid"; };
  readonly 61445: { readonly value: 61445; readonly enumName: "SpectralExcludedByStream"; readonly displayName: "Spectral Excluded By Stream"; readonly category: "Invalid"; };
};

export declare const MOTELY_ITEM_FORMATS_BY_ENUM_NAME: {
  readonly AbstractJoker: { readonly value: 20504; readonly enumName: "AbstractJoker"; readonly displayName: "Abstract Joker"; readonly category: "Joker"; };
  readonly AceOfClubs: { readonly value: 4108; readonly enumName: "AceOfClubs"; readonly displayName: "Ace of Clubs"; readonly category: "Standardcard"; };
  readonly AceOfDiamonds: { readonly value: 4124; readonly enumName: "AceOfDiamonds"; readonly displayName: "Ace of Diamonds"; readonly category: "Standardcard"; };
  readonly AceOfHearts: { readonly value: 4140; readonly enumName: "AceOfHearts"; readonly displayName: "Ace of Hearts"; readonly category: "Standardcard"; };
  readonly AceOfSpades: { readonly value: 4156; readonly enumName: "AceOfSpades"; readonly displayName: "Ace of Spades"; readonly category: "Standardcard"; };
  readonly Acrobat: { readonly value: 21546; readonly enumName: "Acrobat"; readonly displayName: "Acrobat"; readonly category: "Joker"; };
  readonly AncientJoker: { readonly value: 22533; readonly enumName: "AncientJoker"; readonly displayName: "Ancient Joker"; readonly category: "Joker"; };
  readonly Ankh: { readonly value: 8202; readonly enumName: "Ankh"; readonly displayName: "Ankh"; readonly category: "SpectralCard"; };
  readonly Arrowhead: { readonly value: 21554; readonly enumName: "Arrowhead"; readonly displayName: "Arrowhead"; readonly category: "Joker"; };
  readonly Astronomer: { readonly value: 21566; readonly enumName: "Astronomer"; readonly displayName: "Astronomer"; readonly category: "Joker"; };
  readonly Aura: { readonly value: 8196; readonly enumName: "Aura"; readonly displayName: "Aura"; readonly category: "SpectralCard"; };
  readonly Banner: { readonly value: 20497; readonly enumName: "Banner"; readonly displayName: "Banner"; readonly category: "Joker"; };
  readonly Baron: { readonly value: 22530; readonly enumName: "Baron"; readonly displayName: "Baron"; readonly category: "Joker"; };
  readonly BaseballCard: { readonly value: 22532; readonly enumName: "BaseballCard"; readonly displayName: "Baseball Card"; readonly category: "Joker"; };
  readonly BlackHole: { readonly value: 8209; readonly enumName: "BlackHole"; readonly displayName: "Black Hole"; readonly category: "SpectralCard"; };
  readonly Blackboard: { readonly value: 21517; readonly enumName: "Blackboard"; readonly displayName: "Blackboard"; readonly category: "Joker"; };
  readonly Bloodstone: { readonly value: 21553; readonly enumName: "Bloodstone"; readonly displayName: "Bloodstone"; readonly category: "Joker"; };
  readonly BlueJoker: { readonly value: 20517; readonly enumName: "BlueJoker"; readonly displayName: "Blue Joker"; readonly category: "Joker"; };
  readonly Blueprint: { readonly value: 22535; readonly enumName: "Blueprint"; readonly displayName: "Blueprint"; readonly category: "Joker"; };
  readonly Bootstraps: { readonly value: 21567; readonly enumName: "Bootstraps"; readonly displayName: "Bootstraps"; readonly category: "Joker"; };
  readonly Brainstorm: { readonly value: 22545; readonly enumName: "Brainstorm"; readonly displayName: "Brainstorm"; readonly category: "Joker"; };
  readonly Bull: { readonly value: 21537; readonly enumName: "Bull"; readonly displayName: "Bull"; readonly category: "Joker"; };
  readonly Burglar: { readonly value: 21516; readonly enumName: "Burglar"; readonly displayName: "Burglar"; readonly category: "Joker"; };
  readonly BurntJoker: { readonly value: 22547; readonly enumName: "BurntJoker"; readonly displayName: "Burnt Joker"; readonly category: "Joker"; };
  readonly BusinessCard: { readonly value: 20510; readonly enumName: "BusinessCard"; readonly displayName: "Business Card"; readonly category: "Joker"; };
  readonly Campfire: { readonly value: 22534; readonly enumName: "Campfire"; readonly displayName: "Campfire"; readonly category: "Joker"; };
  readonly Canio: { readonly value: 23552; readonly enumName: "Canio"; readonly displayName: "Canio"; readonly category: "Joker"; };
  readonly CardSharp: { readonly value: 21521; readonly enumName: "CardSharp"; readonly displayName: "Card Sharp"; readonly category: "Joker"; };
  readonly Cartomancer: { readonly value: 21565; readonly enumName: "Cartomancer"; readonly displayName: "Cartomancer"; readonly category: "Joker"; };
  readonly Castle: { readonly value: 21544; readonly enumName: "Castle"; readonly displayName: "Castle"; readonly category: "Joker"; };
  readonly Cavendish: { readonly value: 20522; readonly enumName: "Cavendish"; readonly displayName: "Cavendish"; readonly category: "Joker"; };
  readonly CeremonialDagger: { readonly value: 21507; readonly enumName: "CeremonialDagger"; readonly displayName: "Ceremonial Dagger"; readonly category: "Joker"; };
  readonly Ceres: { readonly value: 16394; readonly enumName: "Ceres"; readonly displayName: "Ceres"; readonly category: "PlanetCard"; };
  readonly Certificate: { readonly value: 21549; readonly enumName: "Certificate"; readonly displayName: "Certificate"; readonly category: "Joker"; };
  readonly ChaostheClown: { readonly value: 20502; readonly enumName: "ChaostheClown"; readonly displayName: "Chaos the Clown"; readonly category: "Joker"; };
  readonly Chicot: { readonly value: 23555; readonly enumName: "Chicot"; readonly displayName: "Chicot"; readonly category: "Joker"; };
  readonly CleverJoker: { readonly value: 20492; readonly enumName: "CleverJoker"; readonly displayName: "Clever Joker"; readonly category: "Joker"; };
  readonly Cloud9: { readonly value: 21527; readonly enumName: "Cloud9"; readonly displayName: "Cloud 9"; readonly category: "Joker"; };
  readonly Constellation: { readonly value: 21519; readonly enumName: "Constellation"; readonly displayName: "Constellation"; readonly category: "Joker"; };
  readonly CraftyJoker: { readonly value: 20494; readonly enumName: "CraftyJoker"; readonly displayName: "Crafty Joker"; readonly category: "Joker"; };
  readonly CrazyJoker: { readonly value: 20488; readonly enumName: "CrazyJoker"; readonly displayName: "Crazy Joker"; readonly category: "Joker"; };
  readonly CreditCard: { readonly value: 20496; readonly enumName: "CreditCard"; readonly displayName: "Credit Card"; readonly category: "Joker"; };
  readonly Cryptid: { readonly value: 8207; readonly enumName: "Cryptid"; readonly displayName: "Cryptid"; readonly category: "SpectralCard"; };
  readonly DNA: { readonly value: 22528; readonly enumName: "DNA"; readonly displayName: "DNA"; readonly category: "Joker"; };
  readonly Death: { readonly value: 12301; readonly enumName: "Death"; readonly displayName: "Death"; readonly category: "TarotCard"; };
  readonly DejaVu: { readonly value: 8203; readonly enumName: "DejaVu"; readonly displayName: "Deja Vu"; readonly category: "SpectralCard"; };
  readonly DelayedGratification: { readonly value: 20505; readonly enumName: "DelayedGratification"; readonly displayName: "Delayed Gratification"; readonly category: "Joker"; };
  readonly DeviousJoker: { readonly value: 20493; readonly enumName: "DeviousJoker"; readonly displayName: "Devious Joker"; readonly category: "Joker"; };
  readonly DietCola: { readonly value: 21538; readonly enumName: "DietCola"; readonly displayName: "Diet Cola"; readonly category: "Joker"; };
  readonly DriversLicense: { readonly value: 22546; readonly enumName: "DriversLicense"; readonly displayName: "Driver\u0027s License"; readonly category: "Joker"; };
  readonly DrollJoker: { readonly value: 20489; readonly enumName: "DrollJoker"; readonly displayName: "Droll Joker"; readonly category: "Joker"; };
  readonly Drunkard: { readonly value: 20532; readonly enumName: "Drunkard"; readonly displayName: "Drunkard"; readonly category: "Joker"; };
  readonly Dusk: { readonly value: 21510; readonly enumName: "Dusk"; readonly displayName: "Dusk"; readonly category: "Joker"; };
  readonly Earth: { readonly value: 16386; readonly enumName: "Earth"; readonly displayName: "Earth"; readonly category: "PlanetCard"; };
  readonly Ectoplasm: { readonly value: 8200; readonly enumName: "Ectoplasm"; readonly displayName: "Ectoplasm"; readonly category: "SpectralCard"; };
  readonly Egg: { readonly value: 20513; readonly enumName: "Egg"; readonly displayName: "Egg"; readonly category: "Joker"; };
  readonly EightBall: { readonly value: 20499; readonly enumName: "EightBall"; readonly displayName: "8 Ball"; readonly category: "Joker"; };
  readonly EightOfClubs: { readonly value: 4102; readonly enumName: "EightOfClubs"; readonly displayName: "8 of Clubs"; readonly category: "Standardcard"; };
  readonly EightOfDiamonds: { readonly value: 4118; readonly enumName: "EightOfDiamonds"; readonly displayName: "8 of Diamonds"; readonly category: "Standardcard"; };
  readonly EightOfHearts: { readonly value: 4134; readonly enumName: "EightOfHearts"; readonly displayName: "8 of Hearts"; readonly category: "Standardcard"; };
  readonly EightOfSpades: { readonly value: 4150; readonly enumName: "EightOfSpades"; readonly displayName: "8 of Spades"; readonly category: "Standardcard"; };
  readonly Eris: { readonly value: 16395; readonly enumName: "Eris"; readonly displayName: "Eris"; readonly category: "PlanetCard"; };
  readonly Erosion: { readonly value: 21533; readonly enumName: "Erosion"; readonly displayName: "Erosion"; readonly category: "Joker"; };
  readonly EvenSteven: { readonly value: 20507; readonly enumName: "EvenSteven"; readonly displayName: "Even Steven"; readonly category: "Joker"; };
  readonly FacelessJoker: { readonly value: 20518; readonly enumName: "FacelessJoker"; readonly displayName: "Faceless Joker"; readonly category: "Joker"; };
  readonly Familiar: { readonly value: 8192; readonly enumName: "Familiar"; readonly displayName: "Familiar"; readonly category: "SpectralCard"; };
  readonly Fibonacci: { readonly value: 21511; readonly enumName: "Fibonacci"; readonly displayName: "Fibonacci"; readonly category: "Joker"; };
  readonly FiveOfClubs: { readonly value: 4099; readonly enumName: "FiveOfClubs"; readonly displayName: "5 of Clubs"; readonly category: "Standardcard"; };
  readonly FiveOfDiamonds: { readonly value: 4115; readonly enumName: "FiveOfDiamonds"; readonly displayName: "5 of Diamonds"; readonly category: "Standardcard"; };
  readonly FiveOfHearts: { readonly value: 4131; readonly enumName: "FiveOfHearts"; readonly displayName: "5 of Hearts"; readonly category: "Standardcard"; };
  readonly FiveOfSpades: { readonly value: 4147; readonly enumName: "FiveOfSpades"; readonly displayName: "5 of Spades"; readonly category: "Standardcard"; };
  readonly FlashCard: { readonly value: 21540; readonly enumName: "FlashCard"; readonly displayName: "Flash Card"; readonly category: "Joker"; };
  readonly FlowerPot: { readonly value: 21558; readonly enumName: "FlowerPot"; readonly displayName: "Flower Pot"; readonly category: "Joker"; };
  readonly FortuneTeller: { readonly value: 20530; readonly enumName: "FortuneTeller"; readonly displayName: "Fortune Teller"; readonly category: "Joker"; };
  readonly FourFingers: { readonly value: 21505; readonly enumName: "FourFingers"; readonly displayName: "Four Fingers"; readonly category: "Joker"; };
  readonly FourOfClubs: { readonly value: 4098; readonly enumName: "FourOfClubs"; readonly displayName: "4 of Clubs"; readonly category: "Standardcard"; };
  readonly FourOfDiamonds: { readonly value: 4114; readonly enumName: "FourOfDiamonds"; readonly displayName: "4 of Diamonds"; readonly category: "Standardcard"; };
  readonly FourOfHearts: { readonly value: 4130; readonly enumName: "FourOfHearts"; readonly displayName: "4 of Hearts"; readonly category: "Standardcard"; };
  readonly FourOfSpades: { readonly value: 4146; readonly enumName: "FourOfSpades"; readonly displayName: "4 of Spades"; readonly category: "Standardcard"; };
  readonly GiftCard: { readonly value: 21531; readonly enumName: "GiftCard"; readonly displayName: "Gift Card"; readonly category: "Joker"; };
  readonly GlassJoker: { readonly value: 21556; readonly enumName: "GlassJoker"; readonly displayName: "Glass Joker"; readonly category: "Joker"; };
  readonly GluttonousJoker: { readonly value: 20484; readonly enumName: "GluttonousJoker"; readonly displayName: "Gluttonous Joker"; readonly category: "Joker"; };
  readonly GoldenJoker: { readonly value: 20533; readonly enumName: "GoldenJoker"; readonly displayName: "Golden Joker"; readonly category: "Joker"; };
  readonly GoldenTicket: { readonly value: 20537; readonly enumName: "GoldenTicket"; readonly displayName: "Golden Ticket"; readonly category: "Joker"; };
  readonly GreedyJoker: { readonly value: 20481; readonly enumName: "GreedyJoker"; readonly displayName: "Greedy Joker"; readonly category: "Joker"; };
  readonly GreenJoker: { readonly value: 20519; readonly enumName: "GreenJoker"; readonly displayName: "Green Joker"; readonly category: "Joker"; };
  readonly Grim: { readonly value: 8193; readonly enumName: "Grim"; readonly displayName: "Grim"; readonly category: "SpectralCard"; };
  readonly GrosMichel: { readonly value: 20506; readonly enumName: "GrosMichel"; readonly displayName: "Gros Michel"; readonly category: "Joker"; };
  readonly Hack: { readonly value: 21513; readonly enumName: "Hack"; readonly displayName: "Hack"; readonly category: "Joker"; };
  readonly HalfJoker: { readonly value: 20495; readonly enumName: "HalfJoker"; readonly displayName: "Half Joker"; readonly category: "Joker"; };
  readonly Hallucination: { readonly value: 20529; readonly enumName: "Hallucination"; readonly displayName: "Hallucination"; readonly category: "Joker"; };
  readonly HangingChad: { readonly value: 20539; readonly enumName: "HangingChad"; readonly displayName: "Hanging Chad"; readonly category: "Joker"; };
  readonly Hex: { readonly value: 8204; readonly enumName: "Hex"; readonly displayName: "Hex"; readonly category: "SpectralCard"; };
  readonly Hiker: { readonly value: 21520; readonly enumName: "Hiker"; readonly displayName: "Hiker"; readonly category: "Joker"; };
  readonly HitTheRoad: { readonly value: 22537; readonly enumName: "HitTheRoad"; readonly displayName: "Hit the Road"; readonly category: "Joker"; };
  readonly Hologram: { readonly value: 21526; readonly enumName: "Hologram"; readonly displayName: "Hologram"; readonly category: "Joker"; };
  readonly IceCream: { readonly value: 20515; readonly enumName: "IceCream"; readonly displayName: "Ice Cream"; readonly category: "Joker"; };
  readonly Immolate: { readonly value: 8201; readonly enumName: "Immolate"; readonly displayName: "Immolate"; readonly category: "SpectralCard"; };
  readonly Incantation: { readonly value: 8194; readonly enumName: "Incantation"; readonly displayName: "Incantation"; readonly category: "SpectralCard"; };
  readonly Invalid: { readonly value: 61440; readonly enumName: "Invalid"; readonly displayName: "Invalid"; readonly category: "Invalid"; };
  readonly InvisibleJoker: { readonly value: 22544; readonly enumName: "InvisibleJoker"; readonly displayName: "Invisible Joker"; readonly category: "Joker"; };
  readonly JackOfClubs: { readonly value: 4105; readonly enumName: "JackOfClubs"; readonly displayName: "Jack of Clubs"; readonly category: "Standardcard"; };
  readonly JackOfDiamonds: { readonly value: 4121; readonly enumName: "JackOfDiamonds"; readonly displayName: "Jack of Diamonds"; readonly category: "Standardcard"; };
  readonly JackOfHearts: { readonly value: 4137; readonly enumName: "JackOfHearts"; readonly displayName: "Jack of Hearts"; readonly category: "Standardcard"; };
  readonly JackOfSpades: { readonly value: 4153; readonly enumName: "JackOfSpades"; readonly displayName: "Jack of Spades"; readonly category: "Standardcard"; };
  readonly Joker: { readonly value: 20480; readonly enumName: "Joker"; readonly displayName: "Joker"; readonly category: "Joker"; };
  readonly JokerExcludedByStream: { readonly value: 61442; readonly enumName: "JokerExcludedByStream"; readonly displayName: "Joker Excluded By Stream"; readonly category: "Invalid"; };
  readonly JokerStencil: { readonly value: 21504; readonly enumName: "JokerStencil"; readonly displayName: "Joker Stencil"; readonly category: "Joker"; };
  readonly JollyJoker: { readonly value: 20485; readonly enumName: "JollyJoker"; readonly displayName: "Jolly Joker"; readonly category: "Joker"; };
  readonly Judgement: { readonly value: 12308; readonly enumName: "Judgement"; readonly displayName: "Judgement"; readonly category: "TarotCard"; };
  readonly Juggler: { readonly value: 20531; readonly enumName: "Juggler"; readonly displayName: "Juggler"; readonly category: "Joker"; };
  readonly Jupiter: { readonly value: 16388; readonly enumName: "Jupiter"; readonly displayName: "Jupiter"; readonly category: "PlanetCard"; };
  readonly Justice: { readonly value: 12296; readonly enumName: "Justice"; readonly displayName: "Justice"; readonly category: "TarotCard"; };
  readonly KingOfClubs: { readonly value: 4107; readonly enumName: "KingOfClubs"; readonly displayName: "King of Clubs"; readonly category: "Standardcard"; };
  readonly KingOfDiamonds: { readonly value: 4123; readonly enumName: "KingOfDiamonds"; readonly displayName: "King of Diamonds"; readonly category: "Standardcard"; };
  readonly KingOfHearts: { readonly value: 4139; readonly enumName: "KingOfHearts"; readonly displayName: "King of Hearts"; readonly category: "Standardcard"; };
  readonly KingOfSpades: { readonly value: 4155; readonly enumName: "KingOfSpades"; readonly displayName: "King of Spades"; readonly category: "Standardcard"; };
  readonly LoyaltyCard: { readonly value: 21509; readonly enumName: "LoyaltyCard"; readonly displayName: "Loyalty Card"; readonly category: "Joker"; };
  readonly Luchador: { readonly value: 21530; readonly enumName: "Luchador"; readonly displayName: "Luchador"; readonly category: "Joker"; };
  readonly LuckyCat: { readonly value: 21536; readonly enumName: "LuckyCat"; readonly displayName: "Lucky Cat"; readonly category: "Joker"; };
  readonly LustyJoker: { readonly value: 20482; readonly enumName: "LustyJoker"; readonly displayName: "Lusty Joker"; readonly category: "Joker"; };
  readonly MadJoker: { readonly value: 20487; readonly enumName: "MadJoker"; readonly displayName: "Mad Joker"; readonly category: "Joker"; };
  readonly Madness: { readonly value: 21522; readonly enumName: "Madness"; readonly displayName: "Madness"; readonly category: "Joker"; };
  readonly MailInRebate: { readonly value: 20528; readonly enumName: "MailInRebate"; readonly displayName: "Mail In Rebate"; readonly category: "Joker"; };
  readonly MarbleJoker: { readonly value: 21508; readonly enumName: "MarbleJoker"; readonly displayName: "Marble Joker"; readonly category: "Joker"; };
  readonly Mars: { readonly value: 16387; readonly enumName: "Mars"; readonly displayName: "Mars"; readonly category: "PlanetCard"; };
  readonly Matador: { readonly value: 21563; readonly enumName: "Matador"; readonly displayName: "Matador"; readonly category: "Joker"; };
  readonly Medium: { readonly value: 8206; readonly enumName: "Medium"; readonly displayName: "Medium"; readonly category: "SpectralCard"; };
  readonly Mercury: { readonly value: 16384; readonly enumName: "Mercury"; readonly displayName: "Mercury"; readonly category: "PlanetCard"; };
  readonly MerryAndy: { readonly value: 21559; readonly enumName: "MerryAndy"; readonly displayName: "Merry Andy"; readonly category: "Joker"; };
  readonly MidasMask: { readonly value: 21529; readonly enumName: "MidasMask"; readonly displayName: "Midas Mask"; readonly category: "Joker"; };
  readonly Mime: { readonly value: 21506; readonly enumName: "Mime"; readonly displayName: "Mime"; readonly category: "Joker"; };
  readonly Misprint: { readonly value: 20500; readonly enumName: "Misprint"; readonly displayName: "Misprint"; readonly category: "Joker"; };
  readonly MrBones: { readonly value: 21545; readonly enumName: "MrBones"; readonly displayName: "Mr. Bones"; readonly category: "Joker"; };
  readonly MysticSummit: { readonly value: 20498; readonly enumName: "MysticSummit"; readonly displayName: "Mystic Summit"; readonly category: "Joker"; };
  readonly Neptune: { readonly value: 16391; readonly enumName: "Neptune"; readonly displayName: "Neptune"; readonly category: "PlanetCard"; };
  readonly NineOfClubs: { readonly value: 4103; readonly enumName: "NineOfClubs"; readonly displayName: "9 of Clubs"; readonly category: "Standardcard"; };
  readonly NineOfDiamonds: { readonly value: 4119; readonly enumName: "NineOfDiamonds"; readonly displayName: "9 of Diamonds"; readonly category: "Standardcard"; };
  readonly NineOfHearts: { readonly value: 4135; readonly enumName: "NineOfHearts"; readonly displayName: "9 of Hearts"; readonly category: "Standardcard"; };
  readonly NineOfSpades: { readonly value: 4151; readonly enumName: "NineOfSpades"; readonly displayName: "9 of Spades"; readonly category: "Standardcard"; };
  readonly NotImplemented: { readonly value: 61441; readonly enumName: "NotImplemented"; readonly displayName: "Not Implemented"; readonly category: "Invalid"; };
  readonly Obelisk: { readonly value: 22531; readonly enumName: "Obelisk"; readonly displayName: "Obelisk"; readonly category: "Joker"; };
  readonly OddTodd: { readonly value: 20508; readonly enumName: "OddTodd"; readonly displayName: "Odd Todd"; readonly category: "Joker"; };
  readonly OnyxAgate: { readonly value: 21555; readonly enumName: "OnyxAgate"; readonly displayName: "Onyx Agate"; readonly category: "Joker"; };
  readonly OopsAll6s: { readonly value: 21560; readonly enumName: "OopsAll6s"; readonly displayName: "Oops! All 6s"; readonly category: "Joker"; };
  readonly Ouija: { readonly value: 8199; readonly enumName: "Ouija"; readonly displayName: "Ouija"; readonly category: "SpectralCard"; };
  readonly Pareidolia: { readonly value: 21514; readonly enumName: "Pareidolia"; readonly displayName: "Pareidolia"; readonly category: "Joker"; };
  readonly Perkeo: { readonly value: 23556; readonly enumName: "Perkeo"; readonly displayName: "Perkeo"; readonly category: "Joker"; };
  readonly Photograph: { readonly value: 20526; readonly enumName: "Photograph"; readonly displayName: "Photograph"; readonly category: "Joker"; };
  readonly PlanetExcludedByStream: { readonly value: 61443; readonly enumName: "PlanetExcludedByStream"; readonly displayName: "Planet Excluded By Stream"; readonly category: "Invalid"; };
  readonly PlanetX: { readonly value: 16393; readonly enumName: "PlanetX"; readonly displayName: "Planet X"; readonly category: "PlanetCard"; };
  readonly Pluto: { readonly value: 16392; readonly enumName: "Pluto"; readonly displayName: "Pluto"; readonly category: "PlanetCard"; };
  readonly Popcorn: { readonly value: 20534; readonly enumName: "Popcorn"; readonly displayName: "Popcorn"; readonly category: "Joker"; };
  readonly QueenOfClubs: { readonly value: 4106; readonly enumName: "QueenOfClubs"; readonly displayName: "Queen of Clubs"; readonly category: "Standardcard"; };
  readonly QueenOfDiamonds: { readonly value: 4122; readonly enumName: "QueenOfDiamonds"; readonly displayName: "Queen of Diamonds"; readonly category: "Standardcard"; };
  readonly QueenOfHearts: { readonly value: 4138; readonly enumName: "QueenOfHearts"; readonly displayName: "Queen of Hearts"; readonly category: "Standardcard"; };
  readonly QueenOfSpades: { readonly value: 4154; readonly enumName: "QueenOfSpades"; readonly displayName: "Queen of Spades"; readonly category: "Standardcard"; };
  readonly RaisedFist: { readonly value: 20501; readonly enumName: "RaisedFist"; readonly displayName: "Raised Fist"; readonly category: "Joker"; };
  readonly Ramen: { readonly value: 21542; readonly enumName: "Ramen"; readonly displayName: "Ramen"; readonly category: "Joker"; };
  readonly RedCard: { readonly value: 20523; readonly enumName: "RedCard"; readonly displayName: "Red Card"; readonly category: "Joker"; };
  readonly ReservedParking: { readonly value: 20527; readonly enumName: "ReservedParking"; readonly displayName: "Reserved Parking"; readonly category: "Joker"; };
  readonly RideTheBus: { readonly value: 20512; readonly enumName: "RideTheBus"; readonly displayName: "Ride the Bus"; readonly category: "Joker"; };
  readonly RiffRaff: { readonly value: 20525; readonly enumName: "RiffRaff"; readonly displayName: "Riff-raff"; readonly category: "Joker"; };
  readonly Rocket: { readonly value: 21528; readonly enumName: "Rocket"; readonly displayName: "Rocket"; readonly category: "Joker"; };
  readonly RoughGem: { readonly value: 21552; readonly enumName: "RoughGem"; readonly displayName: "Rough Gem"; readonly category: "Joker"; };
  readonly Runner: { readonly value: 20514; readonly enumName: "Runner"; readonly displayName: "Runner"; readonly category: "Joker"; };
  readonly Satellite: { readonly value: 21564; readonly enumName: "Satellite"; readonly displayName: "Satellite"; readonly category: "Joker"; };
  readonly Saturn: { readonly value: 16389; readonly enumName: "Saturn"; readonly displayName: "Saturn"; readonly category: "PlanetCard"; };
  readonly ScaryFace: { readonly value: 20503; readonly enumName: "ScaryFace"; readonly displayName: "Scary Face"; readonly category: "Joker"; };
  readonly Scholar: { readonly value: 20509; readonly enumName: "Scholar"; readonly displayName: "Scholar"; readonly category: "Joker"; };
  readonly Seance: { readonly value: 21523; readonly enumName: "Seance"; readonly displayName: "Seance"; readonly category: "Joker"; };
  readonly SeeingDouble: { readonly value: 21562; readonly enumName: "SeeingDouble"; readonly displayName: "Seeing Double"; readonly category: "Joker"; };
  readonly Seltzer: { readonly value: 21543; readonly enumName: "Seltzer"; readonly displayName: "Seltzer"; readonly category: "Joker"; };
  readonly SevenOfClubs: { readonly value: 4101; readonly enumName: "SevenOfClubs"; readonly displayName: "7 of Clubs"; readonly category: "Standardcard"; };
  readonly SevenOfDiamonds: { readonly value: 4117; readonly enumName: "SevenOfDiamonds"; readonly displayName: "7 of Diamonds"; readonly category: "Standardcard"; };
  readonly SevenOfHearts: { readonly value: 4133; readonly enumName: "SevenOfHearts"; readonly displayName: "7 of Hearts"; readonly category: "Standardcard"; };
  readonly SevenOfSpades: { readonly value: 4149; readonly enumName: "SevenOfSpades"; readonly displayName: "7 of Spades"; readonly category: "Standardcard"; };
  readonly ShootTheMoon: { readonly value: 20540; readonly enumName: "ShootTheMoon"; readonly displayName: "Shoot the Moon"; readonly category: "Joker"; };
  readonly Shortcut: { readonly value: 21525; readonly enumName: "Shortcut"; readonly displayName: "Shortcut"; readonly category: "Joker"; };
  readonly Showman: { readonly value: 21557; readonly enumName: "Showman"; readonly displayName: "Showman"; readonly category: "Joker"; };
  readonly Sigil: { readonly value: 8198; readonly enumName: "Sigil"; readonly displayName: "Sigil"; readonly category: "SpectralCard"; };
  readonly SixOfClubs: { readonly value: 4100; readonly enumName: "SixOfClubs"; readonly displayName: "6 of Clubs"; readonly category: "Standardcard"; };
  readonly SixOfDiamonds: { readonly value: 4116; readonly enumName: "SixOfDiamonds"; readonly displayName: "6 of Diamonds"; readonly category: "Standardcard"; };
  readonly SixOfHearts: { readonly value: 4132; readonly enumName: "SixOfHearts"; readonly displayName: "6 of Hearts"; readonly category: "Standardcard"; };
  readonly SixOfSpades: { readonly value: 4148; readonly enumName: "SixOfSpades"; readonly displayName: "6 of Spades"; readonly category: "Standardcard"; };
  readonly SixthSense: { readonly value: 21518; readonly enumName: "SixthSense"; readonly displayName: "Sixth Sense"; readonly category: "Joker"; };
  readonly SlyJoker: { readonly value: 20490; readonly enumName: "SlyJoker"; readonly displayName: "Sly Joker"; readonly category: "Joker"; };
  readonly SmearedJoker: { readonly value: 21550; readonly enumName: "SmearedJoker"; readonly displayName: "Smeared Joker"; readonly category: "Joker"; };
  readonly SmileyFace: { readonly value: 20536; readonly enumName: "SmileyFace"; readonly displayName: "Smiley Face"; readonly category: "Joker"; };
  readonly SockAndBuskin: { readonly value: 21547; readonly enumName: "SockAndBuskin"; readonly displayName: "Sock and Buskin"; readonly category: "Joker"; };
  readonly SpaceJoker: { readonly value: 21515; readonly enumName: "SpaceJoker"; readonly displayName: "Space Joker"; readonly category: "Joker"; };
  readonly SpareTrousers: { readonly value: 21541; readonly enumName: "SpareTrousers"; readonly displayName: "Spare Trousers"; readonly category: "Joker"; };
  readonly SpectralExcludedByStream: { readonly value: 61445; readonly enumName: "SpectralExcludedByStream"; readonly displayName: "Spectral Excluded By Stream"; readonly category: "Invalid"; };
  readonly Splash: { readonly value: 20516; readonly enumName: "Splash"; readonly displayName: "Splash"; readonly category: "Joker"; };
  readonly SquareJoker: { readonly value: 20524; readonly enumName: "SquareJoker"; readonly displayName: "Square Joker"; readonly category: "Joker"; };
  readonly SteelJoker: { readonly value: 21512; readonly enumName: "SteelJoker"; readonly displayName: "Steel Joker"; readonly category: "Joker"; };
  readonly StoneJoker: { readonly value: 21535; readonly enumName: "StoneJoker"; readonly displayName: "Stone Joker"; readonly category: "Joker"; };
  readonly Strength: { readonly value: 12299; readonly enumName: "Strength"; readonly displayName: "Strength"; readonly category: "TarotCard"; };
  readonly Stuntman: { readonly value: 22543; readonly enumName: "Stuntman"; readonly displayName: "Stuntman"; readonly category: "Joker"; };
  readonly Supernova: { readonly value: 20511; readonly enumName: "Supernova"; readonly displayName: "Supernova"; readonly category: "Joker"; };
  readonly Superposition: { readonly value: 20520; readonly enumName: "Superposition"; readonly displayName: "Superposition"; readonly category: "Joker"; };
  readonly Swashbuckler: { readonly value: 20538; readonly enumName: "Swashbuckler"; readonly displayName: "Swashbuckler"; readonly category: "Joker"; };
  readonly Talisman: { readonly value: 8195; readonly enumName: "Talisman"; readonly displayName: "Talisman"; readonly category: "SpectralCard"; };
  readonly TarotExcludedByStream: { readonly value: 61444; readonly enumName: "TarotExcludedByStream"; readonly displayName: "Tarot Excluded By Stream"; readonly category: "Invalid"; };
  readonly Temperance: { readonly value: 12302; readonly enumName: "Temperance"; readonly displayName: "Temperance"; readonly category: "TarotCard"; };
  readonly TenOfClubs: { readonly value: 4104; readonly enumName: "TenOfClubs"; readonly displayName: "10 of Clubs"; readonly category: "Standardcard"; };
  readonly TenOfDiamonds: { readonly value: 4120; readonly enumName: "TenOfDiamonds"; readonly displayName: "10 of Diamonds"; readonly category: "Standardcard"; };
  readonly TenOfHearts: { readonly value: 4136; readonly enumName: "TenOfHearts"; readonly displayName: "10 of Hearts"; readonly category: "Standardcard"; };
  readonly TenOfSpades: { readonly value: 4152; readonly enumName: "TenOfSpades"; readonly displayName: "10 of Spades"; readonly category: "Standardcard"; };
  readonly TheChariot: { readonly value: 12295; readonly enumName: "TheChariot"; readonly displayName: "The Chariot"; readonly category: "TarotCard"; };
  readonly TheDevil: { readonly value: 12303; readonly enumName: "TheDevil"; readonly displayName: "The Devil"; readonly category: "TarotCard"; };
  readonly TheDuo: { readonly value: 22538; readonly enumName: "TheDuo"; readonly displayName: "The Duo"; readonly category: "Joker"; };
  readonly TheEmperor: { readonly value: 12292; readonly enumName: "TheEmperor"; readonly displayName: "The Emperor"; readonly category: "TarotCard"; };
  readonly TheEmpress: { readonly value: 12291; readonly enumName: "TheEmpress"; readonly displayName: "The Empress"; readonly category: "TarotCard"; };
  readonly TheFamily: { readonly value: 22540; readonly enumName: "TheFamily"; readonly displayName: "The Family"; readonly category: "Joker"; };
  readonly TheFool: { readonly value: 12288; readonly enumName: "TheFool"; readonly displayName: "The Fool"; readonly category: "TarotCard"; };
  readonly TheHangedMan: { readonly value: 12300; readonly enumName: "TheHangedMan"; readonly displayName: "The Hanged Man"; readonly category: "TarotCard"; };
  readonly TheHermit: { readonly value: 12297; readonly enumName: "TheHermit"; readonly displayName: "The Hermit"; readonly category: "TarotCard"; };
  readonly TheHierophant: { readonly value: 12293; readonly enumName: "TheHierophant"; readonly displayName: "The Hierophant"; readonly category: "TarotCard"; };
  readonly TheHighPriestess: { readonly value: 12290; readonly enumName: "TheHighPriestess"; readonly displayName: "The High Priestess"; readonly category: "TarotCard"; };
  readonly TheIdol: { readonly value: 21561; readonly enumName: "TheIdol"; readonly displayName: "The Idol"; readonly category: "Joker"; };
  readonly TheLovers: { readonly value: 12294; readonly enumName: "TheLovers"; readonly displayName: "The Lovers"; readonly category: "TarotCard"; };
  readonly TheMagician: { readonly value: 12289; readonly enumName: "TheMagician"; readonly displayName: "The Magician"; readonly category: "TarotCard"; };
  readonly TheMoon: { readonly value: 12306; readonly enumName: "TheMoon"; readonly displayName: "The Moon"; readonly category: "TarotCard"; };
  readonly TheOrder: { readonly value: 22541; readonly enumName: "TheOrder"; readonly displayName: "The Order"; readonly category: "Joker"; };
  readonly TheSoul: { readonly value: 8208; readonly enumName: "TheSoul"; readonly displayName: "The Soul"; readonly category: "SpectralCard"; };
  readonly TheStar: { readonly value: 12305; readonly enumName: "TheStar"; readonly displayName: "The Star"; readonly category: "TarotCard"; };
  readonly TheSun: { readonly value: 12307; readonly enumName: "TheSun"; readonly displayName: "The Sun"; readonly category: "TarotCard"; };
  readonly TheTower: { readonly value: 12304; readonly enumName: "TheTower"; readonly displayName: "The Tower"; readonly category: "TarotCard"; };
  readonly TheTribe: { readonly value: 22542; readonly enumName: "TheTribe"; readonly displayName: "The Tribe"; readonly category: "Joker"; };
  readonly TheTrio: { readonly value: 22539; readonly enumName: "TheTrio"; readonly displayName: "The Trio"; readonly category: "Joker"; };
  readonly TheWheelOfFortune: { readonly value: 12298; readonly enumName: "TheWheelOfFortune"; readonly displayName: "The Wheel of Fortune"; readonly category: "TarotCard"; };
  readonly TheWorld: { readonly value: 12309; readonly enumName: "TheWorld"; readonly displayName: "The World"; readonly category: "TarotCard"; };
  readonly ThreeOfClubs: { readonly value: 4097; readonly enumName: "ThreeOfClubs"; readonly displayName: "3 of Clubs"; readonly category: "Standardcard"; };
  readonly ThreeOfDiamonds: { readonly value: 4113; readonly enumName: "ThreeOfDiamonds"; readonly displayName: "3 of Diamonds"; readonly category: "Standardcard"; };
  readonly ThreeOfHearts: { readonly value: 4129; readonly enumName: "ThreeOfHearts"; readonly displayName: "3 of Hearts"; readonly category: "Standardcard"; };
  readonly ThreeOfSpades: { readonly value: 4145; readonly enumName: "ThreeOfSpades"; readonly displayName: "3 of Spades"; readonly category: "Standardcard"; };
  readonly Throwback: { readonly value: 21551; readonly enumName: "Throwback"; readonly displayName: "Throwback"; readonly category: "Joker"; };
  readonly ToDoList: { readonly value: 20521; readonly enumName: "ToDoList"; readonly displayName: "To Do List"; readonly category: "Joker"; };
  readonly ToTheMoon: { readonly value: 21534; readonly enumName: "ToTheMoon"; readonly displayName: "To the Moon"; readonly category: "Joker"; };
  readonly TradingCard: { readonly value: 21539; readonly enumName: "TradingCard"; readonly displayName: "Trading Card"; readonly category: "Joker"; };
  readonly Trance: { readonly value: 8205; readonly enumName: "Trance"; readonly displayName: "Trance"; readonly category: "SpectralCard"; };
  readonly Triboulet: { readonly value: 23553; readonly enumName: "Triboulet"; readonly displayName: "Triboulet"; readonly category: "Joker"; };
  readonly Troubadour: { readonly value: 21548; readonly enumName: "Troubadour"; readonly displayName: "Troubadour"; readonly category: "Joker"; };
  readonly TurtleBean: { readonly value: 21532; readonly enumName: "TurtleBean"; readonly displayName: "Turtle Bean"; readonly category: "Joker"; };
  readonly TwoOfClubs: { readonly value: 4096; readonly enumName: "TwoOfClubs"; readonly displayName: "2 of Clubs"; readonly category: "Standardcard"; };
  readonly TwoOfDiamonds: { readonly value: 4112; readonly enumName: "TwoOfDiamonds"; readonly displayName: "2 of Diamonds"; readonly category: "Standardcard"; };
  readonly TwoOfHearts: { readonly value: 4128; readonly enumName: "TwoOfHearts"; readonly displayName: "2 of Hearts"; readonly category: "Standardcard"; };
  readonly TwoOfSpades: { readonly value: 4144; readonly enumName: "TwoOfSpades"; readonly displayName: "2 of Spades"; readonly category: "Standardcard"; };
  readonly Uranus: { readonly value: 16390; readonly enumName: "Uranus"; readonly displayName: "Uranus"; readonly category: "PlanetCard"; };
  readonly Vagabond: { readonly value: 22529; readonly enumName: "Vagabond"; readonly displayName: "Vagabond"; readonly category: "Joker"; };
  readonly Vampire: { readonly value: 21524; readonly enumName: "Vampire"; readonly displayName: "Vampire"; readonly category: "Joker"; };
  readonly Venus: { readonly value: 16385; readonly enumName: "Venus"; readonly displayName: "Venus"; readonly category: "PlanetCard"; };
  readonly WalkieTalkie: { readonly value: 20535; readonly enumName: "WalkieTalkie"; readonly displayName: "Walkie Talkie"; readonly category: "Joker"; };
  readonly WeeJoker: { readonly value: 22536; readonly enumName: "WeeJoker"; readonly displayName: "Wee Joker"; readonly category: "Joker"; };
  readonly WilyJoker: { readonly value: 20491; readonly enumName: "WilyJoker"; readonly displayName: "Wily Joker"; readonly category: "Joker"; };
  readonly Wraith: { readonly value: 8197; readonly enumName: "Wraith"; readonly displayName: "Wraith"; readonly category: "SpectralCard"; };
  readonly WrathfulJoker: { readonly value: 20483; readonly enumName: "WrathfulJoker"; readonly displayName: "Wrathful Joker"; readonly category: "Joker"; };
  readonly Yorick: { readonly value: 23554; readonly enumName: "Yorick"; readonly displayName: "Yorick"; readonly category: "Joker"; };
  readonly ZanyJoker: { readonly value: 20486; readonly enumName: "ZanyJoker"; readonly displayName: "Zany Joker"; readonly category: "Joker"; };
};

export type MotelyItemEnumName = keyof typeof MOTELY_ITEM_FORMATS_BY_ENUM_NAME;
export type MotelyItemPackedValue = keyof typeof MOTELY_ITEM_FORMATS_BY_VALUE;
