export const rootKeys = [
  "id",
  "name",
  "description",
  "author",
  "dateCreated",
  "deck",
  "stake",
  "seeds",
  "must",
  "should",
  "mustNot",
];

export const sharedClauseKeys = [
  "ante",
  "antes",
  "min",
  "max",
  "score",
  "label",
  "sources",
  "with",
  "luck",
  "vouchers",
];

export const clauseKeys = [
  "joker",
  "jokers",
  "commonJoker",
  "commonJokers",
  "uncommonJoker",
  "uncommonJokers",
  "rareJoker",
  "rareJokers",
  "legendaryJoker",
  "legendaryJokers",
  "edition",
  "stickers",
  "shopItems",
  "boosterPacks",
  "arcanaPacks",
  "spectralPacks",
  "soulCard",
  "requireMega",
  "requireMegaPack",
  "soulCardOnly",
  "soulEditionRolls",
  "standardCard",
  "rank",
  "suit",
  "enhancement",
  "seal",
  "startingDraw",
  "luckyMoney",
  "luckyMult",
  "misprintMult",
  "wheelOfFortune",
  "grosMichelExtinct",
  "cavendishExtinct",
  "spaceLevelup",
  "businessPayout",
  "bloodstoneTrigger",
  "parkingPayout",
  "glassDestroy",
  "wheelStaysFlipped",
  "rolls",
  "mult",
  "value",
];

export const logicKeys = ["and", "or", "clauses"];

export const allKeys = Array.from(
  new Set([...rootKeys, ...sharedClauseKeys, ...clauseKeys, ...logicKeys]),
);
