using Motely.Filters.Jaml;

var entries = JamlDiscriminatorRegistry.Entries;
var discriminators = entries.Keys.OrderBy(k => k, StringComparer.OrdinalIgnoreCase);

Console.WriteLine("// <auto-generated/> Written by Motely.Schema from JamlSchema + JamlDiscriminatorRegistry.");
Console.WriteLine("// Re-generate: dotnet run --project Motely.Schema");
Console.WriteLine();
Console.WriteLine("export const JamlSchema = {");

foreach (var key in discriminators)
{
    var entry = entries[key];
    var clauseKeys = JamlSchema.ClauseKeysFor(key);
    var sourceKeys = JamlSchema.SourceKeysFor(key);
    var rollsAreInline = JamlSchema.RollsAreInlineFor(key);
    var rollsDefault = JamlSchema.RollsDefaultFor(key);

    Console.WriteLine($"  {key}: {{");
    Console.WriteLine($"    clauseType: \"{entry.ClauseType.Name}\",");
    if (entry.ValueEnumType is not null)
        Console.WriteLine($"    valueEnum: \"{entry.ValueEnumType.Name}\",");
    if (entry.SourceConfigType is not null)
        Console.WriteLine($"    sourceConfigType: \"{entry.SourceConfigType.Name}\",");
    if (rollsAreInline)
        Console.WriteLine("    rollsAreInline: true,");
    if (rollsDefault is not null)
        Console.WriteLine($"    rollsDefault: [{string.Join(", ", rollsDefault)}],");
    if (clauseKeys.Length > 0)
        Console.WriteLine($"    clauseKeys: [{string.Join(", ", clauseKeys.Select(k => $"\"{k}\""))}],");
    if (sourceKeys?.Length > 0)
        Console.WriteLine($"    sourceKeys: [{string.Join(", ", sourceKeys.Select(k => $"\"{k}\""))}],");
    Console.WriteLine("  },");
}

Console.WriteLine("};");
Console.WriteLine();
Console.WriteLine("export type JamlDiscriminator = keyof typeof JamlSchema;");
Console.WriteLine("export type JamlClauseType = typeof JamlSchema[JamlDiscriminator][\"clauseType\"];");
