// Motely.Schema — emits jaml-lang/src/generated.ts, jaml-lsp/syntaxes/jaml.tmLanguage.json,
// and jaml-lsp/schemas/jaml.schema.json.
//
// Run:  dotnet run --project Motely.Schema  (from repo root)
//       dotnet run --project Motely.Schema -- --dry-run  (show paths only)
//
// All data comes directly from JamlVocab (static typed tables) + Enum.GetNames<T>().
// Zero regex. Zero text scraping.

using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Motely.Filters.Jaml;

// ── Locate repo root ──────────────────────────────────────────────────────────

var thisDir = AppContext.BaseDirectory;
var repoRoot = Path.GetFullPath(Path.Combine(thisDir, "..", "..", "..", ".."));
if (!File.Exists(Path.Combine(repoRoot, "Motely.slnx")))
    throw new InvalidOperationException($"Could not locate repo root from '{thisDir}'.");

bool dryRun = args.Contains("--dry-run");

// ── Data — straight from JamlVocab ───────────────────────────────────────────

var enumMap               = JamlVocab.GetAllEnums();
var discriminators        = JamlVocab.Discriminators;
var rootKeys              = JamlVocab.RootKeys;
var discValueEnum         = JamlVocab.DiscriminatorValueEnum;   // disc → enum name | null
var discClauseKeys        = JamlVocab.DiscriminatorClauseKeys;  // disc → allowed clause props
var discSourceKeys        = JamlVocab.DiscriminatorSourceKeys;  // disc → allowed source props

// Union of all clause-level keys across every discriminator
var allClauseLevelKeys = discClauseKeys.Values
    .SelectMany(v => v)
    .Distinct(StringComparer.OrdinalIgnoreCase)
    .OrderBy(k => k)
    .ToArray();

// Union of all source keys
var allSourceKeys = discSourceKeys.Values
    .SelectMany(v => v)
    .Distinct(StringComparer.OrdinalIgnoreCase)
    .ToArray();

Console.WriteLine($"Loaded {enumMap.Count} enums, {discriminators.Count} discriminators");

// ── Output paths ──────────────────────────────────────────────────────────────

var generatedTsPath = Path.Combine(repoRoot, "jaml-lang", "src", "generated.ts");
var tmGrammarPath   = Path.Combine(repoRoot, "jaml-lsp", "syntaxes", "jaml.tmLanguage.json");
var jsonSchemaPath  = Path.Combine(repoRoot, "jaml-lsp", "schemas", "jaml.schema.json");

if (dryRun)
{
    Console.WriteLine($"[dry-run] {generatedTsPath}");
    Console.WriteLine($"[dry-run] {tmGrammarPath}");
    Console.WriteLine($"[dry-run] {jsonSchemaPath}");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(generatedTsPath)!);
Directory.CreateDirectory(Path.GetDirectoryName(tmGrammarPath)!);
Directory.CreateDirectory(Path.GetDirectoryName(jsonSchemaPath)!);

// ── generated.ts ──────────────────────────────────────────────────────────────

var ts = new StringBuilder();
ts.AppendLine("// AUTO-GENERATED by Motely.Schema — DO NOT EDIT.");
ts.AppendLine("// Source of truth: Motely/Filters/Jaml/JamlVocab.cs + enum reflection.");
ts.AppendLine();

ts.AppendLine("export const Enums: Record<string, readonly string[]> = {");
foreach (var (name, members) in enumMap.OrderBy(kv => kv.Key))
    ts.AppendLine($"    {name}: [{string.Join(", ", members.Select(m => $"\"{m}\""))}],");
ts.AppendLine("};");
ts.AppendLine();

ts.AppendLine($"export const Discriminators: readonly string[] = [{string.Join(", ", discriminators.OrderBy(k => k).Select(k => $"\"{k}\""))}];");
ts.AppendLine($"export const RootKeys: readonly string[] = [{string.Join(", ", rootKeys.OrderBy(k => k).Select(k => $"\"{k}\""))}];");
ts.AppendLine($"export const AllClauseLevelKeys: readonly string[] = [{string.Join(", ", allClauseLevelKeys.Select(k => $"\"{k}\""))}];");
ts.AppendLine();

ts.AppendLine("export const RootValueEnums: Record<string, string> = { deck: \"MotelyDeck\", stake: \"MotelyStake\" };");
ts.AppendLine();

// discriminatorValueEnum — only emit entries that have a non-null enum name
ts.AppendLine("export const DiscriminatorValueEnum: Record<string, string> = {");
foreach (var (disc, enumName) in discValueEnum.Where(kv => kv.Value != null))
    ts.AppendLine($"    \"{disc}\": \"{enumName}\",");
ts.AppendLine("};");
ts.AppendLine();

// Clause-level keys whose value is an enum (suit, rank, edition, seal, …) — the single
// source of truth the validator & completions read, so they stop keeping their own copies.
ts.AppendLine("export const ClauseKeyValueEnum: Record<string, string> = {");
foreach (var (key, enumName) in JamlVocab.ClauseKeyValueEnum.OrderBy(kv => kv.Key))
    ts.AppendLine($"    \"{key}\": \"{enumName}\",");
ts.AppendLine("};");
ts.AppendLine();

ts.AppendLine("export const DiscriminatorClauseKeys: Record<string, readonly string[]> = {");
foreach (var (disc, keys) in discClauseKeys)
    ts.AppendLine($"    \"{disc}\": [{string.Join(", ", keys.Select(k => $"\"{k}\""))}],");
ts.AppendLine("};");
ts.AppendLine();

ts.AppendLine("export const DiscriminatorSourceKeys: Record<string, readonly string[]> = {");
foreach (var (disc, keys) in discSourceKeys)
    ts.AppendLine($"    \"{disc}\": [{string.Join(", ", keys.Select(k => $"\"{k}\""))}],");
ts.AppendLine("};");

File.WriteAllText(generatedTsPath, ts.ToString(), Encoding.UTF8);
Console.WriteLine($"wrote {Path.GetRelativePath(repoRoot, generatedTsPath)}");

// ── TextMate grammar ──────────────────────────────────────────────────────────

var allEnumMembers = enumMap.Values.SelectMany(v => v).Distinct().OrderByDescending(m => m.Length).ToList();
var allNonDiscKeys = rootKeys.Concat(allClauseLevelKeys).Concat(allSourceKeys)
    .Distinct(StringComparer.OrdinalIgnoreCase).ToList();

string Alt(IEnumerable<string> words) =>
    $@"\b(?:{string.Join("|", words.Distinct().OrderByDescending(w => w.Length).Select(Regex.Escape))})(?=\s*:)";

string AltBare(IEnumerable<string> words) =>
    $@"\b(?:{string.Join("|", words.Distinct().OrderByDescending(w => w.Length).Select(Regex.Escape))})\b";

var grammar = new
{
    name = "JAML",
    scopeName = "source.jaml",
    fileTypes = new[] { "jaml" },
    patterns = new object[]
    {
        new { match = "#.*$",                                         name = "comment.line.number-sign.jaml" },
        new { match = Alt(discriminators),                            name = "entity.name.tag.discriminator.jaml" },
        new { match = Alt(allNonDiscKeys),                            name = "keyword.other.key.jaml" },
        new { match = AltBare(allEnumMembers.Append("Any")),          name = "support.constant.enum.jaml" },
        new { match = @"\b(?:true|false)\b",                          name = "constant.language.boolean.jaml" },
        new { match = @"\b\d+\b",                                     name = "constant.numeric.jaml" },
        new { match = "\"[^\"]*\"",                                   name = "string.quoted.double.jaml" },
        new { match = "'[^']*'",                                      name = "string.quoted.single.jaml" },
    }
};

File.WriteAllText(tmGrammarPath,
    JsonSerializer.Serialize(grammar, new JsonSerializerOptions { WriteIndented = true }),
    Encoding.UTF8);
Console.WriteLine($"wrote {Path.GetRelativePath(repoRoot, tmGrammarPath)}");

// ── JSON Schema ───────────────────────────────────────────────────────────────

// Enum-backed keys come straight from JamlVocab.ClauseKeyValueEnum (the single source of
// truth) — never a hand-kept list here, which is what let `rank` lose its enum while `suit`
// kept it. `stickers` is the lone array-of-enum key.
object PropSchema(string key)
{
    if (JamlVocab.ClauseKeyValueEnum.TryGetValue(key, out var enumName))
    {
        var members = enumMap.GetValueOrDefault(enumName, []);
        return key == "stickers"
            ? new { type = "array", items = new { type = "string", @enum = members } }
            : (object)new { type = "string", @enum = members };
    }

    return key switch
    {
        "ante"            => new { type = "integer", minimum = 1, maximum = 8 },
        "antes"           => new { type = "array",   items = new { type = "integer", minimum = 1, maximum = 8 } },
        "min" or "max" or "score" or "soulEditionRolls" or "value"
                          => new { type = "integer" },
        "shopItems"       => new { type = "array", items = new { type = "integer" } },
        "soulCardOnly"    => new { type = "boolean" },
        "sources"         => new { type = "object" },
        _                 => new { type = "string" }   // label and any free-text key
    };
}

object DiscValueSchema(string disc)
{
    if (discValueEnum.TryGetValue(disc, out var en) && en != null && enumMap.TryGetValue(en, out var members))
        return new { type = "string", @enum = (object)members.Concat(["Any"]).ToArray() };
    return new { type = new[] { "string", "array" } };
}

var clauseAnyOf = discriminators.OrderBy(d => d).Select(disc =>
{
    var props = new Dictionary<string, object> { [disc] = DiscValueSchema(disc) };
    if (discClauseKeys.TryGetValue(disc, out var ck))
        foreach (var k in ck) props[k] = PropSchema(k);
    return (object)new { required = new[] { disc }, properties = props, additionalProperties = false };
}).ToList();

var rootProps = new Dictionary<string, object>
{
    ["id"]          = new { type = "string" },
    ["name"]        = new { type = "string" },
    ["description"] = new { type = "string" },
    ["author"]      = new { type = "string" },
    ["seeds"]       = new { type = "array", items = new { type = "string" } },
    ["deck"]        = new { type = "string", @enum = enumMap.GetValueOrDefault("MotelyDeck", []) },
    ["stake"]       = new { type = "string", @enum = enumMap.GetValueOrDefault("MotelyStake", []) },
    ["must"]        = new { type = "array", items = new { anyOf = clauseAnyOf } },
    ["should"]      = new { type = "array", items = new { anyOf = clauseAnyOf } },
    ["mustNot"]     = new { type = "array", items = new { anyOf = clauseAnyOf } },
};

// Drift guard: every JamlVocab.RootKeys entry must be described above, or the schema
// would silently drop a real key. Fail generation loudly instead.
var missingRoot = rootKeys.Where(k => !rootProps.ContainsKey(k)).ToArray();
if (missingRoot.Length > 0)
    throw new InvalidOperationException(
        $"RootKeys missing from JSON-schema root properties: {string.Join(", ", missingRoot)}. " +
        "Add them in Motely.Schema/Program.cs.");

var jsonSchema = new
{
    title = "JAML Filter",
    description = "Jimbo's Ante Markup Language — Balatro seed filter",
    type = "object",
    additionalProperties = false,
    properties = rootProps,
};

File.WriteAllText(jsonSchemaPath,
    JsonSerializer.Serialize(jsonSchema, new JsonSerializerOptions { WriteIndented = true }),
    Encoding.UTF8);
Console.WriteLine($"wrote {Path.GetRelativePath(repoRoot, jsonSchemaPath)}");

return 0;
