// Motely.Schema — emits jaml-lang/src/generated.ts and jaml-lsp/syntaxes/jaml.tmLanguage.json.
//
// Run:  dotnet run --project Motely.Schema  (from repo root)
//       dotnet run --project Motely.Schema -- --dry-run  (show paths only)
//
// All data comes directly from JamlVocab (static typed tables) + Enum.GetNames<T>().
// Zero regex. Zero text scraping.

using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Motely.Filters.Jaml;

// ── Locate repo root ──────────────────────────────────────────────────────────

var thisDir = AppContext.BaseDirectory;
var repoRoot = Path.GetFullPath(Path.Combine(thisDir, "..", "..", "..", ".."));
if (!File.Exists(Path.Combine(repoRoot, "Motely.slnx")))
    throw new InvalidOperationException($"Could not locate repo root from '{thisDir}'.");

bool dryRun = args.Contains("--dry-run");

// ── Data — straight from JamlVocab ───────────────────────────────────────────

var enumMap               = JamlVocab.GetAllEnums();
var discriminators        = JamlVocab.Discriminators;
var rootKeys              = JamlVocab.RootKeys;
var discValueEnum         = JamlVocab.DiscriminatorValueEnum;   // disc → enum name | null
var discClauseKeys        = JamlVocab.DiscriminatorClauseKeys;  // disc → allowed clause props
var discSourceKeys        = JamlVocab.DiscriminatorSourceKeys;  // disc → allowed source props

// Union of all clause-level keys across every discriminator
var allClauseLevelKeys = discClauseKeys.Values
    .SelectMany(v => v)
    .Distinct(StringComparer.OrdinalIgnoreCase)
    .OrderBy(k => k)
    .ToArray();

// Union of all source keys
var allSourceKeys = discSourceKeys.Values
    .SelectMany(v => v)
    .Distinct(StringComparer.OrdinalIgnoreCase)
    .ToArray();

Console.WriteLine($"Loaded {enumMap.Count} enums, {discriminators.Count} discriminators");

// ── Output paths ──────────────────────────────────────────────────────────────

var generatedTsPath = Path.Combine(repoRoot, "jaml-lang", "src", "generated.ts");
var tmGrammarPath   = Path.Combine(repoRoot, "jaml-lsp", "syntaxes", "jaml.tmLanguage.json");

if (dryRun)
{
    Console.WriteLine($"[dry-run] {generatedTsPath}");
    Console.WriteLine($"[dry-run] {tmGrammarPath}");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(generatedTsPath)!);
Directory.CreateDirectory(Path.GetDirectoryName(tmGrammarPath)!);

// ── generated.ts ──────────────────────────────────────────────────────────────

var ts = new StringBuilder();
ts.AppendLine("// AUTO-GENERATED by Motely.Schema — DO NOT EDIT.");
ts.AppendLine("// Source of truth: Motely/Filters/Jaml/JamlVocab.cs + enum reflection.");
ts.AppendLine();

ts.AppendLine("export const Enums: Record<string, readonly string[]> = {");
foreach (var (name, members) in enumMap.OrderBy(kv => kv.Key))
    ts.AppendLine($"    {name}: [{string.Join(", ", members.Select(m => $"\"{m}\""))}],");
ts.AppendLine("};");
ts.AppendLine();

ts.AppendLine($"export const Discriminators: readonly string[] = [{string.Join(", ", discriminators.OrderBy(k => k).Select(k => $"\"{k}\""))}];");
ts.AppendLine($"export const RootKeys: readonly string[] = [{string.Join(", ", rootKeys.OrderBy(k => k).Select(k => $"\"{k}\""))}];");
ts.AppendLine($"export const AllClauseLevelKeys: readonly string[] = [{string.Join(", ", allClauseLevelKeys.Select(k => $"\"{k}\""))}];");
ts.AppendLine();

ts.AppendLine("export const RootValueEnums: Record<string, string> = { deck: \"MotelyDeck\", stake: \"MotelyStake\" };");
ts.AppendLine();

// discriminatorValueEnum — only emit entries that have a non-null enum name
ts.AppendLine("export const DiscriminatorValueEnum: Record<string, string> = {");
foreach (var (disc, enumName) in discValueEnum.Where(kv => kv.Value != null))
    ts.AppendLine($"    \"{disc}\": \"{enumName}\",");
ts.AppendLine("};");
ts.AppendLine();

// Clause-level keys whose value is an enum (suit, rank, edition, seal, …) — the single
// source of truth the validator & completions read, so they stop keeping their own copies.
ts.AppendLine("export const ClauseKeyValueEnum: Record<string, string> = {");
foreach (var (key, enumName) in JamlVocab.ClauseKeyValueEnum.OrderBy(kv => kv.Key))
    ts.AppendLine($"    \"{key}\": \"{enumName}\",");
ts.AppendLine("};");
ts.AppendLine();

ts.AppendLine("export const DiscriminatorClauseKeys: Record<string, readonly string[]> = {");
foreach (var (disc, keys) in discClauseKeys)
    ts.AppendLine($"    \"{disc}\": [{string.Join(", ", keys.Select(k => $"\"{k}\""))}],");
ts.AppendLine("};");
ts.AppendLine();

ts.AppendLine("export const DiscriminatorSourceKeys: Record<string, readonly string[]> = {");
foreach (var (disc, keys) in discSourceKeys)
    ts.AppendLine($"    \"{disc}\": [{string.Join(", ", keys.Select(k => $"\"{k}\""))}],");
ts.AppendLine("};");

File.WriteAllText(generatedTsPath, ts.ToString(), Encoding.UTF8);
Console.WriteLine($"wrote {Path.GetRelativePath(repoRoot, generatedTsPath)}");

// ── TextMate grammar ──────────────────────────────────────────────────────────

var allEnumMembers = enumMap.Values.SelectMany(v => v).Distinct().OrderByDescending(m => m.Length).ToList();
var allNonDiscKeys = rootKeys.Concat(allClauseLevelKeys).Concat(allSourceKeys)
    .Distinct(StringComparer.OrdinalIgnoreCase).ToList();

string Alt(IEnumerable<string> words) =>
    $@"\b(?:{string.Join("|", words.Distinct().OrderByDescending(w => w.Length).Select(Regex.Escape))})(?=\s*:)";

string AltBare(IEnumerable<string> words) =>
    $@"\b(?:{string.Join("|", words.Distinct().OrderByDescending(w => w.Length).Select(Regex.Escape))})\b";

var grammar = new
{
    name = "JAML",
    scopeName = "source.jaml",
    fileTypes = new[] { "jaml" },
    patterns = new object[]
    {
        new { match = "#.*$",                                         name = "comment.line.number-sign.jaml" },
        new { match = Alt(discriminators),                            name = "entity.name.tag.discriminator.jaml" },
        new { match = Alt(allNonDiscKeys),                            name = "keyword.other.key.jaml" },
        new { match = AltBare(allEnumMembers.Append("Any")),          name = "support.constant.enum.jaml" },
        new { match = @"\b(?:true|false)\b",                          name = "constant.language.boolean.jaml" },
        new { match = @"\b\d+\b",                                     name = "constant.numeric.jaml" },
        new { match = "\"[^\"]*\"",                                   name = "string.quoted.double.jaml" },
        new { match = "'[^']*'",                                      name = "string.quoted.single.jaml" },
    }
};

File.WriteAllText(tmGrammarPath,
    JsonSerializer.Serialize(grammar, new JsonSerializerOptions { WriteIndented = true }),
    Encoding.UTF8);
Console.WriteLine($"wrote {Path.GetRelativePath(repoRoot, tmGrammarPath)}");

return 0;
