// AUTO-GEN DRIVER (hand-written; its OUTPUT is generated).
//
// Reads the MotelySingleSearchContext.*.cs partials and emits
// `src/streams.generated.ts` — the canonical inventory of EVERY stream the
// single-seed engine exposes. This is the "completeness contract" map: the
// universe of sources a Jamlyzer walk must materialize and a JAML clause can
// reference. Like gen-vocab.mjs, the C# engine is the source of truth; nobody
// hand-lists streams again (that's how the old coverage report rotted).
//
//   node codegen/gen-streams.mjs
//
// Re-run whenever a stream is added/removed on the C# side. CI can run it and
// fail if `git diff --exit-code src/streams.generated.ts` is dirty.

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative, basename } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");
const engineDir = join(repoRoot, "Motely");
const outFile = join(here, "..", "src", "streams.generated.ts");

// A "stream" is a public Create*Stream factory. Its consumers (GetNext*/Get*)
// are how you pull values out; we capture the factory as the identity of the
// stream and classify by the file it lives in.
const FACTORY_RE = /public\s+([A-Za-z0-9_]+)\s+(Create[A-Za-z0-9_]*Stream)\s*\(/g;

// Category = the partial-class suffix: MotelySingleSearchContext.<Category>.cs
function categoryOf(file) {
  const m = basename(file).match(/^MotelySingleSearchContext\.([A-Za-z]+)\.cs$/);
  return m ? m[1] : "Core";
}

const files = readdirSync(engineDir)
  .filter((f) => /^MotelySingleSearchContext\.[A-Za-z]+\.cs$/.test(f))
  .sort();

const streams = []; // { name, returns, category, source }
for (const f of files) {
  const src = readFileSync(join(engineDir, f), "utf8");
  const category = categoryOf(f);
  const source = relative(repoRoot, join(engineDir, f)).replace(/\\/g, "/");
  const seen = new Set();
  let m;
  while ((m = FACTORY_RE.exec(src)) !== null) {
    const [, returns, name] = m;
    if (seen.has(name)) continue; // collapse overloads
    seen.add(name);
    streams.push({ name, returns, category, source });
  }
}

streams.sort((a, b) =>
  a.category === b.category
    ? a.name.localeCompare(b.name)
    : a.category.localeCompare(b.category)
);

const banner =
  `// AUTO-GENERATED by codegen/gen-streams.mjs — DO NOT EDIT BY HAND.\n` +
  `// Source of truth: Motely/MotelySingleSearchContext.*.cs\n` +
  `// Regenerate: node codegen/gen-streams.mjs\n\n`;

const lines = streams
  .map(
    (s) =>
      `  { name: ${JSON.stringify(s.name)}, returns: ${JSON.stringify(
        s.returns
      )}, category: ${JSON.stringify(s.category)} },`
  )
  .join("\n");

const ts =
  banner +
  `export interface EngineStream {\n` +
  `  /** The Create*Stream factory on MotelySingleSearchContext. */\n` +
  `  readonly name: string;\n` +
  `  /** The stream struct it returns. */\n` +
  `  readonly returns: string;\n` +
  `  /** Partial-class suffix: Boss, Jokers, Tarot, Spectral, Planet, Misc, ... */\n` +
  `  readonly category: string;\n` +
  `}\n\n` +
  `export const ENGINE_STREAMS = [\n${lines}\n] as const satisfies readonly EngineStream[];\n\n` +
  `export type EngineStreamName = (typeof ENGINE_STREAMS)[number]["name"];\n`;

writeFileSync(outFile, ts);

const byCat = {};
for (const s of streams) byCat[s.category] = (byCat[s.category] ?? 0) + 1;
const summary = Object.entries(byCat)
  .map(([c, n]) => `${c}=${n}`)
  .join("  ");
console.log(`wrote ${relative(repoRoot, outFile).replace(/\\/g, "/")}`);
console.log(`streams (${streams.length}): ${summary}`);
