// AUTO-GEN DRIVER (this file is hand-written; its OUTPUT is generated).
//
// Reads the C# enums in Motely/Enums + the JAML clause model and emits
// `src/vocab.generated.ts` — the single source of truth for every value you can
// TYPE in a .jaml file (joker names, vouchers, tarots, decks, editions, ...).
//
// The C# enums are the source of truth. We extract *names* only (the YAML
// accepts the enum member name as a string, e.g. `joker: WeeJoker`), so the
// computed bit-flag VALUES on MotelyJoker are irrelevant here. Numeric decode
// tables for the packed-int PARSED output are a separate follow-up (see README).
//
//   node codegen/gen-vocab.mjs
//
// Re-run whenever a joker/voucher/etc. is added on the C# side. CI can run it
// and fail if `git diff --exit-code src/vocab.generated.ts` is dirty.

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", ".."); // jaml-lang/codegen -> jaml-lang -> repo
const enumsDir = join(repoRoot, "Motely", "Enums");
const outFile = join(here, "..", "src", "vocab.generated.ts");

/** Strip C# comments + attributes so only enum members remain. */
function clean(body) {
  return body
    .replace(/\/\*[\s\S]*?\*\//g, "") // block comments
    .replace(/\/\/.*$/gm, "")         // line + /// doc comments
    .replace(/\[[^\]]*\]/g, "");      // [Flags], [JsonIgnore], etc.
}

/** Extract { enumName: string[] } from a C# source file. */
function extractEnums(src) {
  const out = {};
  // enum bodies never contain a nested `}`, so [^}]* is a safe body capture.
  const re = /\benum\s+([A-Za-z_]\w*)\s*(?::\s*[A-Za-z_][\w.]*\s*)?\{([^}]*)\}/g;
  let m;
  while ((m = re.exec(src)) !== null) {
    const [, name, rawBody] = m;
    const members = clean(rawBody)
      .split(",")
      .map((seg) => seg.split("=")[0].trim()) // drop "= <value>"
      .filter((id) => /^[A-Za-z_]\w*$/.test(id));
    if (members.length) out[name] = members;
  }
  return out;
}

const files = readdirSync(enumsDir).filter((f) => f.endsWith(".cs"));
const all = {};
const sources = [];
for (const f of files.sort()) {
  const src = readFileSync(join(enumsDir, f), "utf8");
  const found = extractEnums(src);
  if (Object.keys(found).length) sources.push(relative(repoRoot, join(enumsDir, f)));
  Object.assign(all, found);
}

const names = Object.keys(all).sort();
const banner =
  `// AUTO-GENERATED by codegen/gen-vocab.mjs — DO NOT EDIT BY HAND.\n` +
  `// Source of truth: ${sources.length} file(s) under Motely/Enums.\n` +
  `// Regenerate: node codegen/gen-vocab.mjs\n\n`;

let ts = banner;
for (const name of names) {
  const arr = all[name].map((v) => JSON.stringify(v)).join(", ");
  ts += `export const ${name} = [${arr}] as const;\n`;
  ts += `export type ${name} = (typeof ${name})[number];\n\n`;
}

writeFileSync(outFile, ts);

const summary = names.map((n) => `${n}=${all[n].length}`).join("  ");
console.log(`wrote ${relative(repoRoot, outFile)}`);
console.log(`enums (${names.length}): ${summary}`);
