using System;
using System.Collections.Generic;

namespace Motely;

/// <summary>
/// Result row returned from search result queries.
/// Contains seed, score, and optional tally columns.
/// </summary>
public class MotelySearchResultRow
{
    public string Seed { get; set; } = "";
    public int Score { get; set; }
    public List<int>? Tallies { get; set; }
}

/// <summary>
/// Extended search interface that includes result access.
/// This is the primary interface consumers should use - it combines
/// search control (start/pause/cancel) with result access (query results).
/// 
/// Motely owns all database operations - consumers just call GetResults().
/// </summary>
public interface IMotelySearchContext : IMotelySearch
{
    /// <summary>
    /// Unique identifier for this search instance.
    /// Generated by Motely, not the consumer.
    /// </summary>
    string SearchId { get; }
    
    /// <summary>
    /// Identifier for the filter used in this search.
    /// Derived from filter name + deck + stake.
    /// </summary>
    string FilterId { get; }
    
    /// <summary>
    /// Number of results found so far.
    /// Motely queries its internal storage - consumer doesn't need to know how.
    /// </summary>
    int ResultCount { get; }
    
    /// <summary>
    /// Column names for the result data (seed, score, plus tally columns).
    /// </summary>
    IReadOnlyList<string> ColumnNames { get; }
    
    /// <summary>
    /// Get a page of results.
    /// Motely handles all database/storage operations internally.
    /// </summary>
    /// <param name="offset">Number of rows to skip</param>
    /// <param name="limit">Maximum number of rows to return</param>
    /// <returns>List of result rows</returns>
    List<MotelySearchResultRow> GetResults(int offset, int limit);
    
    /// <summary>
    /// Get top results ordered by score descending.
    /// </summary>
    /// <param name="limit">Maximum number of results</param>
    /// <returns>Top scoring results</returns>
    List<MotelySearchResultRow> GetTopResults(int limit = 1000);
}
