export type Binary<T> = {
    write: Write<T>;
    read: Read<T>;
    arrayCtor?: TypedArrayCtor;
};
type Write<T> = (writer: Writer, value: T) => void;
type Read<T> = (reader: Reader) => T | null;
type TypedArray = Uint8Array | Int8Array | Uint16Array | Int16Array | Uint32Array | Int32Array | BigInt64Array | Float32Array | Float64Array;
type TypedArrayCtor = new (length: number) => TypedArray;
export declare function serialize<T>(value: T | null | undefined, type: Binary<T>): bigint;
export declare function deserialize<T>(handle: bigint | null | undefined, type: Binary<T>): T | null;
export declare function binary<T>(write: Write<T>, read: Read<T>, arrayCtor?: TypedArrayCtor): Binary<T>;
export declare const types: {
    Boolean: Binary<boolean>;
    Byte: Binary<number>;
    SByte: Binary<number>;
    Int16: Binary<number>;
    UInt16: Binary<number>;
    Int32: Binary<number>;
    UInt32: Binary<number>;
    Int64: Binary<bigint>;
    UInt64: Binary<number>;
    IntPtr: Binary<number>;
    Single: Binary<number>;
    Double: Binary<number>;
    Decimal: Binary<number>;
    Char: Binary<string>;
    String: Binary<string | null | undefined>;
    DateTime: Binary<Date>;
    DateTimeOffset: Binary<Date>;
    Nullable: <T>(inner: Binary<T>) => Binary<T | null | undefined>;
    Array: <T>(element: Binary<T>) => Binary<ArrayLike<T> | null | undefined>;
    List: <T>(element: Binary<T>) => Binary<ArrayLike<T> | null | undefined>;
    Dictionary: <TKey, TValue>(key: Binary<TKey>, value: Binary<TValue>) => Binary<Map<TKey, TValue> | null | undefined>;
};
declare class Writer {
    private heap;
    private ptr;
    private offset;
    private capacity;
    private view;
    constructor();
    detach(): bigint;
    writeMeta(value: number): void;
    writeString(value: string | null | undefined): void;
    writeBytes(value: Uint8Array): void;
    writeByte(value: number): void;
    writeSByte(value: number): void;
    writeBool(value: boolean): void;
    writeUInt16(value: number): void;
    writeInt16(value: number): void;
    writeUInt32(value: number): void;
    writeInt32(value: number): void;
    writeUInt64(value: bigint | number): void;
    writeInt64(value: bigint | number): void;
    writeSingle(value: number): void;
    writeDouble(value: number): void;
    private ensure;
    private refreshHeapView;
}
declare class Reader {
    private readonly heap;
    private readonly ptr;
    private offset;
    private view;
    constructor(handle: bigint);
    dispose(): void;
    readMeta(): number;
    readString(): string | null;
    readBytes(destination: Uint8Array): void;
    readByte(): number;
    readSByte(): number;
    readBool(): boolean;
    readUInt16(): number;
    readInt16(): number;
    readUInt32(): number;
    readInt32(): number;
    readUInt64(): bigint;
    readInt64(): bigint;
    readSingle(): number;
    readDouble(): number;
}
export {};
