<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BootsharpName>motely</BootsharpName>
    <BootsharpPublishDirectory>bin/motely</BootsharpPublishDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bootsharp" />
    <PackageReference Include="Bootsharp.Inject" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Motely/Motely.csproj" />
  </ItemGroup>

</Project>
